export const DEFAULT_PORTFOLIO_ITEMS = [
  {
    id: "ibhip",
    title: "CITYFIT AI",
    category: "AI \ud53c\ud2b8\ub2c8\uc2a4 \ud3ec\ud2b8\ud3f4\ub9ac\uc624",
    status: "\uc2e4\uc11c\ube44\uc2a4 \ubc30\ud3ec",
    stack: "Vercel \u00b7 AI \ud53c\ud2b8\ub2c8\uc2a4 \u00b7 \ubc18\uc751\ud615 \uc6f9",
    description:
      "AI \ud53c\ud2b8\ub2c8\uc2a4 \ube44\uc8fc\uc5bc\uacfc \uc2a4\ud29c\ub514\uc624\ud615 \uc11c\ube44\uc2a4\ub97c \ubcf4\uc5ec\uc8fc\ub294 \uc2e4\uc11c\ube44\uc2a4 \uc0ac\uc774\ud2b8\uc785\ub2c8\ub2e4. \uc784\ubca0\ub4dc\uac00 \ub9c9\ud788\uba74 \uc0c8 \ucc3d \uc5f4\uae30\ub85c \ud655\uc778\ud560 \uc218 \uc788\uc2b5\ub2c8\ub2e4.",
    embedSrc: "https://ibhip.vercel.app/",
    desktopImage: "",
    mobileImage: "",
    highlights: ["AI \ud53c\ud2b8\ub2c8\uc2a4", "\uc2e4\uc11c\ube44\uc2a4", "Vercel \ubc30\ud3ec", "\ubc18\uc751\ud615"],
    visible: true,
    order: 9999,
  },
  {
    id: "aim-furniture",
    title: "에임가구",
    category: "실제 제작 포트폴리오",
    status: "내부 임베드",
    stack: "Next.js · React · 가구 쇼룸",
    description:
      "원목 가구 브랜드의 쇼룸형 웹사이트입니다. 메인 갤러리, 컬렉션, 공간 배치 미리보기, 마감 비교 흐름을 포트폴리오 안에서 바로 확인할 수 있게 연결했습니다.",
    embedSrc: "/portfolio/aim-furniture/site/index.html",
    desktopImage: "/portfolio/aim-furniture/site/site/hero-main.jpg",
    mobileImage: "/portfolio/aim-furniture/site/site/placement-hero.jpg",
    highlights: ["가구 쇼룸", "공간 배치", "마감 비교", "이미지 생성 흐름"],
    visible: true,
    order: 0,
  },
  {
    id: "serene-market-shop",
    title: "Serene Market Shop",
    category: "쇼핑몰 포트폴리오",
    status: "내부 임베드",
    stack: "HTML · CSS · JavaScript · 장바구니",
    description:
      "라이프스타일 쇼핑몰 데모입니다. 30개 상품, 카테고리 필터, 장바구니 저장, 배송 정보 입력, 결제 직전 주문 확인 흐름까지 한 화면에서 테스트할 수 있습니다.",
    embedSrc: "/portfolio/serene-market-shop/site/index.html",
    desktopImage: "/portfolio/serene-market-shop/home-desktop.png",
    mobileImage: "/portfolio/serene-market-shop/home-mobile.png",
    highlights: ["30개 상품", "카테고리 필터", "장바구니", "주문 확인"],
    visible: true,
    order: 1,
  },
  {
    id: "redline-diagonal-layout",
    title: "Redline Diagonal Brand",
    category: "쇼핑몰 포트폴리오",
    status: "내부 임베드",
    stack: "HTML · CSS · JavaScript · 장바구니",
    description:
      "크로스핏/스포츠 브랜드 쇼핑몰 데모입니다. 생성형 상품 이미지, 카테고리 필터, 장바구니, 브랜드 영상 모달까지 연결해 실제 쇼핑몰처럼 둘러볼 수 있게 구성했습니다.",
    embedSrc: "/portfolio/redline-diagonal-layout/site/index.html",
    desktopImage: "/portfolio/redline-diagonal-layout/home-desktop.png",
    mobileImage: "/portfolio/redline-diagonal-layout/home-mobile.png",
    highlights: ["AI 상품 이미지", "상품 필터", "장바구니", "반응형"],
    visible: true,
    order: 2,
  },
  {
    id: "deoksonglaw",
    title: "법무법인 덕송 회생파산센터",
    category: "외부 사이트 포트폴리오",
    status: "외부 임베드",
    stack: "법률 · 회생파산 · 상담형 웹사이트",
    description:
      "법무법인 덕송 회생파산센터 공식 사이트입니다. 법률 상담형 구조와 전문 서비스 안내 흐름을 포트폴리오에서 바로 확인할 수 있도록 연결했습니다.",
    embedSrc: "https://www.deoksonglaw.com/index.html",
    desktopImage: "/portfolio/deoksonglaw/home-desktop.png",
    mobileImage: "/portfolio/deoksonglaw/home-mobile.png",
    highlights: ["법률 상담", "회생파산", "전문 서비스", "외부 임베드"],
    visible: true,
    order: 3,
  },
  {
    id: "ydh-dothome",
    title: "예를다함상조",
    category: "외부 사이트 포트폴리오",
    status: "외부 임베드",
    stack: "상조 · 장례 서비스 · 안내형 웹사이트",
    description:
      "예를다함상조 외부 사이트입니다. 서비스 소개, 안내형 콘텐츠, 상담 연결 흐름을 포트폴리오 내부 임베드로 확인할 수 있게 등록했습니다.",
    embedSrc: "https://sinnaru.dothome.co.kr/ydh/index.php",
    desktopImage: "/portfolio/ydh-dothome/home-desktop.png",
    mobileImage: "/portfolio/ydh-dothome/home-mobile.png",
    highlights: ["상조 서비스", "안내형 구성", "상담 연결", "외부 임베드"],
    visible: true,
    order: 4,
  },
  {
    id: "onemindbath",
    title: "같은마음바스",
    category: "외부 사이트 포트폴리오",
    status: "외부 임베드",
    stack: "욕실 · 리모델링 · 시공 상담형 웹사이트",
    description:
      "같은마음바스 공식 사이트입니다. 욕실 시공/리모델링 브랜드의 상품·상담·브랜드 소개 흐름을 포트폴리오 카드와 임베드 화면으로 연결했습니다.",
    embedSrc: "https://onemindbath.com/",
    desktopImage: "/portfolio/onemindbath/home-desktop.png",
    mobileImage: "/portfolio/onemindbath/home-mobile.png",
    highlights: ["욕실 시공", "리모델링", "브랜드 소개", "외부 임베드"],
    visible: true,
    order: 5,
  },
];
