const img = (style, slug, kind) => `/generated/pages/${style}--${slug}--${kind}.png`;

const themes = {
  neoSun: {
    bg: "#f7e45d",
    surface: "#fffdf4",
    panel: "rgba(255, 252, 241, 0.84)",
    text: "#121212",
    muted: "#5d5649",
    accent: "#ff6b6b",
    accentSoft: "#7dd3fc",
    line: "rgba(18, 18, 18, 0.16)",
    shadow: "10px 10px 0 rgba(18, 18, 18, 0.88)",
    buttonText: "#121212",
  },
  monoStone: {
    bg: "#f3f0e8",
    surface: "#ffffff",
    panel: "rgba(255, 255, 255, 0.86)",
    text: "#101828",
    muted: "#667085",
    accent: "#111827",
    accentSoft: "#e7ebf0",
    line: "rgba(17, 24, 39, 0.08)",
    shadow: "0 22px 46px rgba(15, 23, 42, 0.1)",
    buttonText: "#ffffff",
  },
  monoClinic: {
    bg: "#f5f3ef",
    surface: "#ffffff",
    panel: "rgba(255, 255, 255, 0.9)",
    text: "#161b26",
    muted: "#6c7689",
    accent: "#1d2939",
    accentSoft: "#d5dde8",
    line: "rgba(22, 27, 38, 0.08)",
    shadow: "0 22px 46px rgba(15, 23, 42, 0.08)",
    buttonText: "#ffffff",
  },
  studioWarm: {
    bg: "#efe9df",
    surface: "#fcf9f5",
    panel: "rgba(252, 249, 245, 0.88)",
    text: "#221d18",
    muted: "#65594b",
    accent: "#2e241c",
    accentSoft: "#d9ccb8",
    line: "rgba(34, 29, 24, 0.12)",
    shadow: "0 22px 46px rgba(34, 29, 24, 0.1)",
    buttonText: "#ffffff",
  },
  popRush: {
    bg: "#221537",
    surface: "#2d1b46",
    panel: "rgba(255, 255, 255, 0.12)",
    text: "#ffffff",
    muted: "rgba(255, 255, 255, 0.74)",
    accent: "#ffd84d",
    accentSoft: "#ff7ccf",
    line: "rgba(255, 255, 255, 0.16)",
    shadow: "0 28px 60px rgba(10, 8, 20, 0.35)",
    buttonText: "#111111",
  },
  signalNight: {
    bg: "#07101d",
    surface: "#0e1b33",
    panel: "rgba(10, 22, 42, 0.82)",
    text: "#ecfbff",
    muted: "rgba(203, 241, 255, 0.76)",
    accent: "#39d5ff",
    accentSoft: "#ff6fe4",
    line: "rgba(57, 213, 255, 0.18)",
    shadow: "0 0 42px rgba(57, 213, 255, 0.1)",
    buttonText: "#071018",
  },
  paperWarm: {
    bg: "#f7f1e6",
    surface: "#fffaf2",
    panel: "rgba(255, 250, 242, 0.9)",
    text: "#231d17",
    muted: "#6d6154",
    accent: "#f5c24f",
    accentSoft: "#9fd7f6",
    line: "rgba(35, 29, 23, 0.1)",
    shadow: "0 18px 34px rgba(35, 29, 23, 0.12)",
    buttonText: "#231d17",
  },
  grainStone: {
    bg: "#e8ddd0",
    surface: "#f8f2ea",
    panel: "rgba(248, 242, 234, 0.84)",
    text: "#2c231d",
    muted: "#6b5f53",
    accent: "#3c2c20",
    accentSoft: "#d6c3b2",
    line: "rgba(44, 35, 29, 0.12)",
    shadow: "0 18px 36px rgba(44, 35, 29, 0.1)",
    buttonText: "#ffffff",
  },
  organicSoft: {
    bg: "#eef5e7",
    surface: "#f9fcf4",
    panel: "rgba(249, 252, 244, 0.84)",
    text: "#23301f",
    muted: "#55674f",
    accent: "#24311f",
    accentSoft: "#cfe6bf",
    line: "rgba(35, 48, 31, 0.1)",
    shadow: "0 18px 36px rgba(35, 48, 31, 0.08)",
    buttonText: "#ffffff",
  },
  playBright: {
    bg: "#fff2a9",
    surface: "#fff8d3",
    panel: "rgba(255, 248, 211, 0.84)",
    text: "#121212",
    muted: "#4f4b43",
    accent: "#0f3bd9",
    accentSoft: "#ff79b0",
    line: "rgba(18, 18, 18, 0.12)",
    shadow: "0 20px 34px rgba(18, 18, 18, 0.14)",
    buttonText: "#ffffff",
  },
  chromePearl: {
    bg: "#d8dee8",
    surface: "#f8fbff",
    panel: "rgba(255, 255, 255, 0.5)",
    text: "#151b26",
    muted: "#5d6879",
    accent: "#1c2430",
    accentSoft: "#bcc6d6",
    line: "rgba(255, 255, 255, 0.6)",
    shadow: "0 24px 44px rgba(15, 23, 42, 0.1)",
    buttonText: "#ffffff",
  },
  cafeWarm: {
    bg: "#f4ead9",
    surface: "#fff8ef",
    panel: "rgba(255, 248, 239, 0.86)",
    text: "#2b221a",
    muted: "#6a5c4f",
    accent: "#5d3b24",
    accentSoft: "#e8c498",
    line: "rgba(43, 34, 26, 0.1)",
    shadow: "0 20px 34px rgba(43, 34, 26, 0.1)",
    buttonText: "#ffffff",
  },
};

export const showcasePages = [
  {
    id: "sneaker-drop",
    brand: "RIFT/01",
    industry: "스니커즈 드롭 스토어",
    summary: "오늘 드롭 · AI 사이즈 · 장바구니",
    backdrop: "neo",
    theme: themes.neoSun,
    nav: ["드롭", "사이즈", "룩북", "장바구니"],
    card: {
      size: "wide",
      tone: "neo",
      eyebrow: "드롭 스토어",
      title: "오늘 드롭",
      summary: "사이즈 추천부터 결제까지",
      widgets: ["20:00", "270", "92%"],
    },
    hero: {
      eyebrow: "오늘 발매",
      title: "오늘 드롭, 지금 사이즈",
      subtitle: "놓치지 않게 바로 고르는 화면",
      primary: "지금 담기",
      secondary: "사이즈 보기",
      badges: ["빠른 결제", "AI 사이즈", "룩북"],
    },
    stats: [
      ["03:12:45", "남은 시간"],
      ["270", "추천 사이즈"],
      ["92%", "적중률"],
    ],
    images: {
      hero: img("neo-brutal", "sneaker-drop", "brand"),
      product: img("neo-brutal", "sneaker-drop", "product"),
      scene: img("neo-brutal", "sneaker-drop", "scene"),
    },
    drops: [
      ["Aero Runner", "240-285", "229,000원"],
      ["Frame High", "화이트 / 블랙", "269,000원"],
      ["Cargo Shell Set", "신발 + 팬츠", "189,000원"],
    ],
    miniPanels: [
      ["AI 사이즈", "270 / 발볼 보통"],
      ["오늘 룩", "오프화이트 팬츠"],
      ["출고", "오늘 바로"],
    ],
    quickTools: ["사이즈 추천", "룩 매치", "즉시 결제"],
  },
  {
    id: "supplement-brand",
    brand: "PUNCH FUEL",
    industry: "퍼포먼스 보충제 브랜드",
    summary: "루틴 빌더 · 성분 비교 · 구독",
    backdrop: "neo",
    theme: themes.neoSun,
    nav: ["루틴", "성분", "구독", "결제"],
    card: {
      size: "square",
      tone: "neo",
      eyebrow: "보충제",
      title: "루틴 빌더",
      summary: "목표별 조합 추천",
      widgets: ["7:00", "2종", "49,000"],
    },
    hero: {
      eyebrow: "루틴 시작",
      title: "운동 전, 운동 후, 잠들기 전",
      subtitle: "한 화면에서 바로 맞추는 루틴",
      primary: "루틴 만들기",
      secondary: "구독 보기",
      badges: ["성분 비교", "정기구독", "AI 추천"],
    },
    stats: [
      ["2종", "오늘 루틴"],
      ["14일", "스타터 박스"],
      ["4.9", "재구매"],
    ],
    images: {
      hero: img("neo-brutal", "supplement-brand", "brand"),
      product: img("neo-brutal", "supplement-brand", "product"),
      scene: img("neo-brutal", "supplement-brand", "scene"),
    },
    routines: [
      ["근력", "웨이 + 프리", "119,000원"],
      ["컷팅", "L카르 + 쉐이크", "98,000원"],
      ["회복", "슬립 + 마그네슘", "69,000원"],
    ],
    compareRows: [
      ["단백질", "24g", "31g"],
      ["카페인", "150mg", "0mg"],
      ["당류", "1g", "3g"],
    ],
    plans: ["주 3회 루틴", "출근 전 루틴", "구독 리필"],
  },
  {
    id: "boxing-gym",
    brand: "UPPERCUT CLUB",
    industry: "복싱짐 멤버십",
    summary: "체험 예약 · 코치 매칭 · 수업 시간표",
    backdrop: "neo",
    theme: themes.neoSun,
    nav: ["수업", "코치", "체험", "가입"],
    card: {
      size: "tall",
      tone: "neo",
      eyebrow: "복싱짐",
      title: "오늘 체험",
      summary: "시간표부터 코치까지",
      widgets: ["19:30", "입문반", "3좌석"],
    },
    hero: {
      eyebrow: "체험 등록",
      title: "오늘 저녁, 바로 한 번",
      subtitle: "체험 수업을 먼저 고르는 복싱짐",
      primary: "체험 예약",
      secondary: "코치 보기",
      badges: ["입문반", "샤워실", "1:1 코칭"],
    },
    stats: [
      ["19:30", "오늘 입문반"],
      ["3", "남은 좌석"],
      ["4.9", "코치 평점"],
    ],
    images: {
      hero: img("neo-brutal", "boxing-gym", "brand"),
      product: img("neo-brutal", "boxing-gym", "product"),
      scene: img("neo-brutal", "boxing-gym", "scene"),
    },
    classSlots: ["19:30 입문", "20:30 미트", "21:30 자유"],
    coaches: ["코치 민", "코치 준", "코치 하"],
    plans: [
      ["체험 1회", "입문 수업", "25,000원"],
      ["주 3회", "정규반", "249,000원"],
      ["1:1 PT", "8회", "520,000원"],
    ],
  },
  {
    id: "wealth-app",
    brand: "CLARO",
    industry: "자산관리 SaaS",
    summary: "대시보드 · 목표 플랜 · 데모",
    backdrop: "minimal",
    theme: themes.monoStone,
    nav: ["대시보드", "목표", "카드", "시작"],
    card: {
      size: "wide",
      tone: "minimal",
      eyebrow: "자산관리",
      title: "흩어진 돈 한 화면",
      summary: "목표 · 지출 · 카드 추천",
      widgets: ["+12%", "8분", "무료"],
    },
    hero: {
      eyebrow: "지출 정리",
      title: "흩어진 계좌, 한 화면",
      subtitle: "복잡한 설명 없이 숫자만 보이는 SaaS",
      primary: "무료 시작",
      secondary: "데모 보기",
      badges: ["자동 분류", "목표 플랜", "카드 추천"],
    },
    stats: [
      ["+12%", "이번 달"],
      ["8분", "주간 사용"],
      ["3개", "목표 진행"],
    ],
    images: {
      hero: img("bold-minimal", "wealth-app", "brand"),
      product: img("bold-minimal", "wealth-app", "product"),
      scene: img("bold-minimal", "wealth-app", "scene"),
    },
    boards: ["생활비", "비상금", "여행"],
    goals: [
      ["유럽 여행", "3,200,000원", "71%"],
      ["비상금", "5,000,000원", "42%"],
      ["대출 상환", "1,800,000원", "66%"],
    ],
    cards: ["생활비 카드", "여행 카드", "구독 관리"],
  },
  {
    id: "skin-clinic",
    brand: "ATELIER SKIN",
    industry: "프리미엄 스킨 클리닉",
    summary: "AI 스캔 · 프로그램 선택 · 예약",
    backdrop: "minimal",
    theme: themes.monoClinic,
    nav: ["프로그램", "의료진", "스캔", "예약"],
    card: {
      size: "tall",
      tone: "minimal",
      eyebrow: "클리닉",
      title: "오늘 상담",
      summary: "스캔부터 일정 선택까지",
      widgets: ["14:00", "톤 리셋", "4.9"],
    },
    hero: {
      eyebrow: "초기 진단",
      title: "스캔 먼저, 상담은 짧게",
      subtitle: "프로그램을 고르기 쉬운 클리닉 화면",
      primary: "상담 예약",
      secondary: "AI 스캔",
      badges: ["의료진", "실시간 일정", "피부 스캔"],
    },
    stats: [
      ["14:00", "다음 상담"],
      ["3개", "추천 프로그램"],
      ["4.9", "방문 평점"],
    ],
    images: {
      hero: img("bold-minimal", "skin-clinic", "brand"),
      product: img("bold-minimal", "skin-clinic", "product"),
      scene: img("bold-minimal", "skin-clinic", "scene"),
    },
    doctors: ["원장 1", "원장 2", "상담실장"],
    programs: [
      ["배리어 리스토어", "진정", "129,000원"],
      ["톤 리셋", "색소", "189,000원"],
      ["월간 멤버십", "루틴 관리", "390,000원"],
    ],
    slots: ["목 14:00", "목 15:30", "금 11:00", "금 16:30"],
  },
  {
    id: "arch-studio",
    brand: "PLAIN GRID",
    industry: "건축 · 인테리어 스튜디오",
    summary: "포트폴리오 · 프로세스 · 브리프",
    backdrop: "grain",
    theme: themes.studioWarm,
    nav: ["작업", "프로세스", "브리프", "문의"],
    card: {
      size: "wide",
      tone: "grain",
      eyebrow: "스튜디오",
      title: "공간 상담",
      summary: "작업물부터 문의까지",
      widgets: ["42평", "6주", "제안서"],
    },
    hero: {
      eyebrow: "프로젝트 문의",
      title: "공간부터 말투까지 정리된 스튜디오",
      subtitle: "작업물, 진행 방식, 문의 흐름을 한 번에",
      primary: "브리프 보내기",
      secondary: "작업 보기",
      badges: ["포트폴리오", "제안서", "실측"],
    },
    stats: [
      ["68", "완료 프로젝트"],
      ["6주", "평균 제안"],
      ["2개", "이번 달 오픈"],
    ],
    images: {
      hero: img("bold-minimal", "arch-studio", "brand"),
      product: img("bold-minimal", "arch-studio", "product"),
      scene: img("bold-minimal", "arch-studio", "scene"),
    },
    works: ["상업 공간", "주거 리뉴얼", "브랜딩 존"],
    process: ["실측", "도면", "제안", "시공"],
    briefRows: ["공간 유형", "예산 범위", "오픈 일정"],
  },
  {
    id: "beauty-flash-sale",
    brand: "MELT POP",
    industry: "뷰티 플래시세일 스토어",
    summary: "컬러 비교 · 세트 구매 · 한정 할인",
    backdrop: "max",
    theme: themes.popRush,
    nav: ["세일", "세트", "발색", "장바구니"],
    card: {
      size: "square",
      tone: "max",
      eyebrow: "플래시세일",
      title: "지금 핫딜",
      summary: "컬러와 할인율이 먼저 보이는 화면",
      widgets: ["40%", "3세트", "24:00"],
    },
    hero: {
      eyebrow: "한정 수량",
      title: "컬러 고르고 바로 세트로",
      subtitle: "할인, 색상, 세트를 한 번에 보는 스토어",
      primary: "세트 담기",
      secondary: "발색 보기",
      badges: ["오늘 특가", "세트 할인", "AI 발색"],
    },
    stats: [
      ["40%", "오늘 할인"],
      ["03:42:11", "남은 시간"],
      ["3개", "세트 구성"],
    ],
    images: {
      hero: img("maximal-pop", "beauty-flash-sale", "brand"),
      product: img("maximal-pop", "beauty-flash-sale", "product"),
      scene: img("maximal-pop", "beauty-flash-sale", "scene"),
    },
    kits: [
      ["캔디 블러 세트", "립 3종", "39,000원"],
      ["글로우 샷", "하이라이터", "22,000원"],
      ["나이트 히트", "메이크업 킷", "76,000원"],
    ],
    shades: ["01 코랄", "02 베리", "03 누드", "04 플럼"],
    checkout: ["세트 할인 12%", "무료 배송", "오늘 출고"],
  },
  {
    id: "festival-page",
    brand: "NOISE WAVE",
    industry: "페스티벌 티켓 페이지",
    summary: "라인업 · 타임테이블 · 티켓",
    backdrop: "retro",
    theme: themes.signalNight,
    nav: ["라인업", "시간표", "티켓", "입장"],
    card: {
      size: "tall",
      tone: "retro",
      eyebrow: "페스티벌",
      title: "타임테이블",
      summary: "라인업과 티켓을 한 화면에",
      widgets: ["VIP", "DAY2", "21:00"],
    },
    hero: {
      eyebrow: "티켓 오픈",
      title: "라인업부터 입장까지",
      subtitle: "복잡한 설명 없이 움직이는 티켓 화면",
      primary: "티켓 구매",
      secondary: "시간표 보기",
      badges: ["라인업", "타임테이블", "현장 가이드"],
    },
    stats: [
      ["DAY2", "추천 일정"],
      ["21:00", "메인 스테이지"],
      ["249,000원", "웨이브 패스"],
    ],
    images: {
      hero: img("maximal-pop", "festival-page", "brand"),
      product: img("maximal-pop", "festival-page", "product"),
      scene: img("maximal-pop", "festival-page", "scene"),
    },
    lineup: ["A-HEAD", "NOVA", "BURNER", "SOUND BOY"],
    timetable: ["18:00 OPEN", "19:40 NOVA", "21:00 A-HEAD", "22:30 BURNER"],
    tickets: [
      ["얼리버드", "입장 전용", "129,000원"],
      ["웨이브 패스", "VIP 존 포함", "249,000원"],
      ["크루 팩", "3인", "339,000원"],
    ],
  },
  {
    id: "creator-club",
    brand: "RALLY HOUSE",
    industry: "크리에이터 멤버십 클럽",
    summary: "가입 플랜 · 혜택 · 커뮤니티",
    backdrop: "max",
    theme: themes.popRush,
    nav: ["플랜", "피드", "혜택", "가입"],
    card: {
      size: "square",
      tone: "max",
      eyebrow: "멤버십",
      title: "클럽 가입",
      summary: "혜택과 피드를 같이 보는 구조",
      widgets: ["월 39,000", "모임", "피드백"],
    },
    hero: {
      eyebrow: "멤버십 오픈",
      title: "작업 피드와 가입 버튼이 같이 있는 클럽",
      subtitle: "포트폴리오, 이벤트, 멤버십을 같은 화면에서",
      primary: "가입하기",
      secondary: "혜택 보기",
      badges: ["포트폴리오", "이벤트", "피드백"],
    },
    stats: [
      ["39,000원", "스타터"],
      ["79,000원", "빌더"],
      ["159,000원", "런치"],
    ],
    images: {
      hero: img("maximal-pop", "creator-club", "brand"),
      product: img("maximal-pop", "creator-club", "product"),
      scene: img("maximal-pop", "creator-club", "scene"),
    },
    passes: [
      ["스타터", "모임 / 채널", "39,000원"],
      ["빌더", "피드백 / 멘토링", "79,000원"],
      ["런치", "브랜드 매칭", "159,000원"],
    ],
    perks: ["주간 피드백", "작업 공유", "콜라보 공고", "오프라인 모임"],
    posts: ["포트폴리오 리뷰", "협업 공고", "다음 모임"],
  },
  {
    id: "ev-mobility",
    brand: "ORBIT E",
    industry: "EV 모빌리티 브랜드",
    summary: "모델 비교 · 시승 예약 · 충전",
    backdrop: "retro",
    theme: themes.signalNight,
    nav: ["모델", "주행", "충전", "예약"],
    card: {
      size: "wide",
      tone: "retro",
      eyebrow: "EV 브랜드",
      title: "모델 비교",
      summary: "주행거리와 예약이 바로 보이는 페이지",
      widgets: ["580km", "GT", "시승"],
    },
    hero: {
      eyebrow: "시승 예약",
      title: "모델부터 충전까지 한 줄로 정리",
      subtitle: "주행, 충전, 예약을 같이 보여주는 EV 페이지",
      primary: "시승 예약",
      secondary: "모델 비교",
      badges: ["주행거리", "충전", "예약"],
    },
    stats: [
      ["580km", "최대 주행"],
      ["24분", "급속 충전"],
      ["토 11:00", "다음 시승"],
    ],
    images: {
      hero: img("retrofuture", "ev-mobility", "brand"),
      product: img("retrofuture", "ev-mobility", "product"),
      scene: img("retrofuture", "ev-mobility", "scene"),
    },
    models: [
      ["Orbit S", "도심형 SUV", "58,900,000원"],
      ["Orbit GT", "퍼포먼스 라인", "71,200,000원"],
      ["Home Charger", "설치 포함", "상담"],
    ],
    specs: ["580km", "4WD", "24분 충전", "ADAS"],
    planner: ["집 충전", "주행 루트", "시승 장소"],
  },
  {
    id: "gaming-gear",
    brand: "VOID ARC",
    industry: "게이밍 기어 스토어",
    summary: "셋업 · 번들 · 장바구니",
    backdrop: "retro",
    theme: themes.signalNight,
    nav: ["기어", "셋업", "사양", "장바구니"],
    card: {
      size: "tall",
      tone: "retro",
      eyebrow: "게이밍 기어",
      title: "셋업 번들",
      summary: "장비보다 전체 셋업이 먼저 보이는 카드",
      widgets: ["144Hz", "RGB", "1,490,000"],
    },
    hero: {
      eyebrow: "셋업 제안",
      title: "책상이 먼저 보이는 기어 스토어",
      subtitle: "마우스 하나보다 전체 셋업을 바로 보여주는 화면",
      primary: "번들 담기",
      secondary: "사양 보기",
      badges: ["셋업 번들", "사양 비교", "AI 매치"],
    },
    stats: [
      ["144Hz", "메인 모니터"],
      ["8ms", "입력 지연"],
      ["1,490,000원", "셋업 번들"],
    ],
    images: {
      hero: img("retrofuture", "gaming-gear", "brand"),
      product: img("retrofuture", "gaming-gear", "product"),
      scene: img("retrofuture", "gaming-gear", "scene"),
    },
    gear: [
      ["Arc 65", "키보드", "189,000원"],
      ["Nebula Pro", "마우스", "129,000원"],
      ["Arena Bundle", "모니터 포함", "1,490,000원"],
    ],
    specs: ["65배열", "초경량", "5K 대응", "RGB 프리셋"],
    cartRows: ["키보드", "마우스", "패드"],
  },
  {
    id: "ai-saas",
    brand: "SIGNAL GRID",
    industry: "AI 워크플로 SaaS",
    summary: "파이프라인 · 사용 사례 · 데모",
    backdrop: "retro",
    theme: themes.signalNight,
    nav: ["플랫폼", "사례", "데모", "도입"],
    card: {
      size: "wide",
      tone: "retro",
      eyebrow: "AI SaaS",
      title: "워크플로",
      summary: "자동화 흐름이 바로 보이는 대시보드",
      widgets: ["파일", "분류", "승인"],
    },
    hero: {
      eyebrow: "실시간 데모",
      title: "파일을 넣으면 흐름이 바로 보이는 AI SaaS",
      subtitle: "기능 설명보다 흐름을 먼저 보여주는 제품 페이지",
      primary: "데모 시작",
      secondary: "사례 보기",
      badges: ["요약", "분류", "승인"],
    },
    stats: [
      ["12초", "첫 결과"],
      ["4단계", "기본 플로우"],
      ["92%", "자동 분류"],
    ],
    images: {
      hero: img("retrofuture", "ai-saas", "brand"),
      product: img("retrofuture", "ai-saas", "product"),
      scene: img("retrofuture", "ai-saas", "scene"),
    },
    flows: ["업로드", "요약", "분류", "승인"],
    useCases: ["제안서 정리", "계약서 분류", "주간 보고"],
    kpis: ["팀당 11시간 절감", "주간 리포트 자동", "권한 분리"],
  },
  {
    id: "indie-bookstore",
    brand: "PAPER NOOK",
    industry: "인디 북스토어",
    summary: "큐레이션 · 선물 세트 · 추천",
    backdrop: "collage",
    theme: themes.paperWarm,
    nav: ["큐레이션", "선물", "추천", "장바구니"],
    card: {
      size: "square",
      tone: "collage",
      eyebrow: "인디 북스토어",
      title: "이번 주 선반",
      summary: "책보다 큐레이션이 먼저 보이는 카드",
      widgets: ["에세이", "3권", "41,000"],
    },
    hero: {
      eyebrow: "이번 주 셀렉션",
      title: "책 한 권보다 선반 전체를 고르게",
      subtitle: "큐레이션과 선물 구성이 먼저 보이는 북스토어",
      primary: "셋 담기",
      secondary: "추천 보기",
      badges: ["큐레이션", "직원 픽", "선물 포장"],
    },
    stats: [
      ["3권", "이번 주 셋"],
      ["41,000원", "에세이 팩"],
      ["무료", "메모 카드"],
    ],
    images: {
      hero: img("collage-paper", "indie-bookstore", "brand"),
      product: img("collage-paper", "indie-bookstore", "product"),
      scene: img("collage-paper", "indie-bookstore", "scene"),
    },
    picks: [
      ["주말 에세이", "3권", "41,000원"],
      ["도시 소설", "2권", "56,000원"],
      ["기프트 랩", "포장", "4,000원"],
    ],
    shelf: ["에세이", "소설", "사진집", "독립출판"],
    notes: ["직원 메모", "선물 추천", "오늘 입고"],
  },
  {
    id: "stationery-shop",
    brand: "CUT & NOTE",
    industry: "문구 스토어",
    summary: "키트 빌더 · 컬러 조합 · 장바구니",
    backdrop: "collage",
    theme: themes.paperWarm,
    nav: ["키트", "컬러", "선물", "장바구니"],
    card: {
      size: "square",
      tone: "collage",
      eyebrow: "문구 스토어",
      title: "키트 빌더",
      summary: "노트와 테이프를 같이 고르는 구조",
      widgets: ["3종", "베스트", "28,000"],
    },
    hero: {
      eyebrow: "데스크 키트",
      title: "노트 하나보다 조합을 먼저",
      subtitle: "색과 구성을 같이 보는 문구 스토어",
      primary: "키트 만들기",
      secondary: "장바구니",
      badges: ["데스크 세트", "컬러 조합", "선물 포장"],
    },
    stats: [
      ["3종", "기본 키트"],
      ["28,000원", "데일리 세트"],
      ["12색", "테이프"],
    ],
    images: {
      hero: img("collage-paper", "stationery-shop", "brand"),
      product: img("collage-paper", "stationery-shop", "product"),
      scene: img("collage-paper", "stationery-shop", "scene"),
    },
    kits: [
      ["데일리 데스크", "노트 + 펜 + 스티커", "28,000원"],
      ["아카이브 노트", "무지 노트", "17,000원"],
      ["무드 테이프 팩", "테이프 세트", "12,000원"],
    ],
    colors: ["버터", "코랄", "스카이", "블랙"],
    basket: ["노트 1", "테이프 2", "스티커 1"],
  },
  {
    id: "local-cafe",
    brand: "TABLE WARM",
    industry: "로컬 카페",
    summary: "메뉴 · 좌석 · 예약",
    backdrop: "hand",
    theme: themes.cafeWarm,
    nav: ["메뉴", "좌석", "예약", "위치"],
    card: {
      size: "wide",
      tone: "hand",
      eyebrow: "로컬 카페",
      title: "오늘 메뉴",
      summary: "메뉴와 좌석을 같이 보는 카페",
      widgets: ["6,500", "창가석", "예약"],
    },
    hero: {
      eyebrow: "오늘 자리",
      title: "메뉴판과 좌석이 같이 보이는 카페",
      subtitle: "음료 고르고 바로 자리까지 잡는 흐름",
      primary: "좌석 예약",
      secondary: "메뉴 보기",
      badges: ["오늘 메뉴", "창가석", "주차"],
    },
    stats: [
      ["6,500원", "시그니처"],
      ["4석", "창가 자리"],
      ["22:00", "마감"],
    ],
    images: {
      hero: img("collage-paper", "local-cafe", "brand"),
      product: img("collage-paper", "local-cafe", "product"),
      scene: img("collage-paper", "local-cafe", "scene"),
    },
    menus: [
      ["크림 솔트 라떼", "시그니처", "6,500원"],
      ["버터 스콘", "베스트", "4,800원"],
      ["브런치 박스", "주말 한정", "19,000원"],
    ],
    seats: ["창가 2인", "안쪽 4인", "작업석 1인"],
    storeRows: ["서울 성수", "주차 2대", "라스트오더 21:30"],
  },
  {
    id: "boutique-hotel",
    brand: "HOTEL STILL",
    industry: "부티크 호텔",
    summary: "객실 · 날짜 선택 · 예약",
    backdrop: "grain",
    theme: themes.grainStone,
    nav: ["객실", "날짜", "패키지", "예약"],
    card: {
      size: "tall",
      tone: "grain",
      eyebrow: "부티크 호텔",
      title: "이번 주 객실",
      summary: "객실과 요금이 바로 보이는 예약 카드",
      widgets: ["2박", "420,000", "체크인"],
    },
    hero: {
      eyebrow: "지금 예약",
      title: "객실 고르고 날짜를 찍는 호텔",
      subtitle: "객실, 날짜, 패키지를 나란히 보여주는 구조",
      primary: "예약하기",
      secondary: "객실 보기",
      badges: ["객실", "체크인", "패키지"],
    },
    stats: [
      ["2박", "추천 일정"],
      ["420,000원", "스위트 기준"],
      ["15:00", "체크인"],
    ],
    images: {
      hero: img("grain-editorial", "boutique-hotel", "brand"),
      product: img("grain-editorial", "boutique-hotel", "product"),
      scene: img("grain-editorial", "boutique-hotel", "scene"),
    },
    rooms: [
      ["스튜디오", "기본 객실", "240,000원"],
      ["스틸 스위트", "라운지 포함", "420,000원"],
      ["주말 패키지", "조식 포함", "310,000원"],
    ],
    dates: ["목 1박", "금 2박", "토 1박"],
    perks: ["조식", "루프탑", "도보 5분"],
  },
  {
    id: "perfume-house",
    brand: "MOSS & AMBER",
    industry: "니치 향수 브랜드",
    summary: "향 노트 · 디스커버리 세트 · 구매",
    backdrop: "grain",
    theme: themes.grainStone,
    nav: ["노트", "세트", "추천", "구매"],
    card: {
      size: "square",
      tone: "grain",
      eyebrow: "향수 브랜드",
      title: "노트 탐색",
      summary: "향부터 세트까지 직관적으로 보는 스토어",
      widgets: ["5종", "39,000", "선물"],
    },
    hero: {
      eyebrow: "향 선택",
      title: "노트부터 세트까지 바로 고르는 향수 페이지",
      subtitle: "향 설명보다 선택 흐름이 먼저 보이는 구조",
      primary: "세트 담기",
      secondary: "향 보기",
      badges: ["디스커버리", "노트", "선물"],
    },
    stats: [
      ["5종", "디스커버리"],
      ["39,000원", "테스트 세트"],
      ["2개", "오늘 추천"],
    ],
    images: {
      hero: img("grain-editorial", "perfume-house", "brand"),
      product: img("grain-editorial", "perfume-house", "product"),
      scene: img("grain-editorial", "perfume-house", "scene"),
    },
    notes: ["앰버", "우디", "모스", "레인"],
    sets: [
      ["디스커버리", "5종 샘플", "39,000원"],
      ["Amber Room", "메인 시그니처", "189,000원"],
      ["Moss Rain", "그린 계열", "182,000원"],
    ],
    matches: ["선물 포장", "레이어링", "취향 추천"],
  },
  {
    id: "furniture-store",
    brand: "MOSS HOME",
    industry: "가구 스토어",
    summary: "룸별 탐색 · 배치 미리보기 · 구매",
    backdrop: "organic",
    theme: themes.organicSoft,
    nav: ["룸", "배치", "번들", "장바구니"],
    card: {
      size: "wide",
      tone: "organic",
      eyebrow: "가구 스토어",
      title: "룸별 탐색",
      summary: "방 기준으로 고르는 가구 페이지",
      widgets: ["거실", "소파", "2,120,000"],
    },
    hero: {
      eyebrow: "공간 기준",
      title: "가구보다 방을 먼저 고르는 스토어",
      subtitle: "배치와 번들을 같이 보여주는 가구 페이지",
      primary: "배치 보기",
      secondary: "세트 보기",
      badges: ["거실", "배치", "AI 추천"],
    },
    stats: [
      ["3개", "추천 배치"],
      ["2,120,000원", "거실 세트"],
      ["당일", "상담 연결"],
    ],
    images: {
      hero: img("organic-soft", "furniture-store", "brand"),
      product: img("organic-soft", "furniture-store", "product"),
      scene: img("organic-soft", "furniture-store", "scene"),
    },
    rooms: ["거실", "침실", "홈오피스"],
    bundles: [
      ["모스 소파", "3인", "1,690,000원"],
      ["페블 테이블", "라운드", "620,000원"],
      ["거실 세트", "소파 + 테이블", "2,120,000원"],
    ],
    placement: ["벽면형", "창가형", "대화형"],
  },
  {
    id: "youth-fashion",
    brand: "BOP BOP",
    industry: "영패션 브랜드",
    summary: "룩 탐색 · 가상 착용 · 장바구니",
    backdrop: "playful",
    theme: themes.playBright,
    nav: ["룩", "가상 착용", "세트", "장바구니"],
    card: {
      size: "tall",
      tone: "playful",
      eyebrow: "패션 브랜드",
      title: "룩 먼저",
      summary: "상품보다 착장으로 고르는 브랜드",
      widgets: ["데님", "후드", "129,000"],
    },
    hero: {
      eyebrow: "가상 착용",
      title: "상품보다 룩이 먼저 보이는 패션 페이지",
      subtitle: "가상 착용과 세트 구매를 같은 흐름에 배치",
      primary: "가상 착용",
      secondary: "세트 담기",
      badges: ["룩북", "AI 착용", "세트 구매"],
    },
    stats: [
      ["2벌", "오늘 세트"],
      ["129,000원", "캠퍼스 세트"],
      ["5초", "가상 착용"],
    ],
    images: {
      hero: img("playful-type", "youth-fashion", "brand"),
      product: img("playful-type", "youth-fashion", "product"),
      scene: img("playful-type", "youth-fashion", "scene"),
    },
    looks: [
      ["Bop Denim", "와이드 데님", "78,000원"],
      ["Flash Hoodie", "후드 집업", "69,000원"],
      ["Campus Set", "후드 + 데님", "129,000원"],
    ],
    sizes: ["S", "M", "L", "XL"],
    cartRows: ["후드 M", "데님 L", "배송 오늘"],
  },
  {
    id: "jewelry-brand",
    brand: "LUNE FORM",
    industry: "주얼리 브랜드",
    summary: "컬렉션 · 맞춤 상담 · 구매",
    backdrop: "chrome",
    theme: themes.chromePearl,
    nav: ["컬렉션", "상담", "선물", "구매"],
    card: {
      size: "wide",
      tone: "chrome",
      eyebrow: "주얼리",
      title: "컬렉션",
      summary: "제품과 상담이 같이 보이는 페이지",
      widgets: ["18K", "780,000", "예약"],
    },
    hero: {
      eyebrow: "맞춤 상담",
      title: "디테일과 상담을 같이 고르는 주얼리 페이지",
      subtitle: "컬렉션, 선물, 상담이 자연스럽게 이어지는 구조",
      primary: "상담 예약",
      secondary: "컬렉션 보기",
      badges: ["18K", "각인", "선물 포장"],
    },
    stats: [
      ["780,000원", "링"],
      ["1,290,000원", "이어링"],
      ["주말", "상담 가능"],
    ],
    images: {
      hero: img("chrome-luxe", "jewelry-brand", "brand"),
      product: img("chrome-luxe", "jewelry-brand", "product"),
      scene: img("chrome-luxe", "jewelry-brand", "scene"),
    },
    collections: [
      ["Moon Line Ring", "18K 화이트 골드", "780,000원"],
      ["Lune Drop", "다이아 포인트", "1,290,000원"],
      ["Bridal Set", "맞춤 상담", "상담"],
    ],
    bespoke: ["디자인 선택", "사이즈 확인", "각인 입력", "수령 일정"],
    consultRows: ["주말 상담", "각인 가능", "선물 포장"],
  },
];
