const buildImage = (style, siteId, kind) => `/generated/pages/${style}--${siteId}--${kind}.png`;

const themes = {
  neoSun: { bg: "#f7e45d", surface: "#fffdf4", panel: "rgba(255, 252, 241, 0.84)", text: "#121212", muted: "#5d5649", accent: "#ff6b6b", accentSoft: "#7dd3fc", line: "rgba(18, 18, 18, 0.16)", shadow: "10px 10px 0 rgba(18, 18, 18, 0.88)", buttonText: "#121212" },
  monoStone: { bg: "#f3f0e8", surface: "#ffffff", panel: "rgba(255, 255, 255, 0.86)", text: "#101828", muted: "#667085", accent: "#111827", accentSoft: "#e7ebf0", line: "rgba(17, 24, 39, 0.08)", shadow: "0 22px 46px rgba(15, 23, 42, 0.1)", buttonText: "#ffffff" },
  monoClinic: { bg: "#f5f3ef", surface: "#ffffff", panel: "rgba(255, 255, 255, 0.9)", text: "#161b26", muted: "#6c7689", accent: "#1d2939", accentSoft: "#d5dde8", line: "rgba(22, 27, 38, 0.08)", shadow: "0 22px 46px rgba(15, 23, 42, 0.08)", buttonText: "#ffffff" },
  studioWarm: { bg: "#efe9df", surface: "#fcf9f5", panel: "rgba(252, 249, 245, 0.88)", text: "#221d18", muted: "#65594b", accent: "#2e241c", accentSoft: "#d9ccb8", line: "rgba(34, 29, 24, 0.12)", shadow: "0 22px 46px rgba(34, 29, 24, 0.1)", buttonText: "#ffffff" },
  popRush: { bg: "#221537", surface: "#2d1b46", panel: "rgba(255, 255, 255, 0.12)", text: "#ffffff", muted: "rgba(255, 255, 255, 0.74)", accent: "#ffd84d", accentSoft: "#ff7ccf", line: "rgba(255, 255, 255, 0.16)", shadow: "0 28px 60px rgba(10, 8, 20, 0.35)", buttonText: "#111111" },
  signalNight: { bg: "#07101d", surface: "#0e1b33", panel: "rgba(10, 22, 42, 0.82)", text: "#ecfbff", muted: "rgba(203, 241, 255, 0.76)", accent: "#39d5ff", accentSoft: "#ff6fe4", line: "rgba(57, 213, 255, 0.18)", shadow: "0 0 42px rgba(57, 213, 255, 0.1)", buttonText: "#071018" },
  ringNight: { bg: "#0b0b12", surface: "#151520", panel: "rgba(18, 18, 28, 0.84)", text: "#f5f7fb", muted: "rgba(225, 232, 244, 0.72)", accent: "#ff6b6b", accentSoft: "#8b5cf6", line: "rgba(255, 255, 255, 0.1)", shadow: "0 28px 64px rgba(4, 4, 10, 0.46)", buttonText: "#111111" },
  paperWarm: { bg: "#f7f1e6", surface: "#fffaf2", panel: "rgba(255, 250, 242, 0.9)", text: "#231d17", muted: "#6d6154", accent: "#f5c24f", accentSoft: "#9fd7f6", line: "rgba(35, 29, 23, 0.1)", shadow: "0 18px 34px rgba(35, 29, 23, 0.12)", buttonText: "#231d17" },
  grainStone: { bg: "#e8ddd0", surface: "#f8f2ea", panel: "rgba(248, 242, 234, 0.84)", text: "#2c231d", muted: "#6b5f53", accent: "#3c2c20", accentSoft: "#d6c3b2", line: "rgba(44, 35, 29, 0.12)", shadow: "0 18px 36px rgba(44, 35, 29, 0.1)", buttonText: "#ffffff" },
  organicSoft: { bg: "#eef5e7", surface: "#f9fcf4", panel: "rgba(249, 252, 244, 0.84)", text: "#23301f", muted: "#55674f", accent: "#24311f", accentSoft: "#cfe6bf", line: "rgba(35, 48, 31, 0.1)", shadow: "0 18px 36px rgba(35, 48, 31, 0.08)", buttonText: "#ffffff" },
  playBright: { bg: "#fff2a9", surface: "#fff8d3", panel: "rgba(255, 248, 211, 0.84)", text: "#121212", muted: "#4f4b43", accent: "#0f3bd9", accentSoft: "#ff79b0", line: "rgba(18, 18, 18, 0.12)", shadow: "0 20px 34px rgba(18, 18, 18, 0.14)", buttonText: "#ffffff" },
  chromePearl: { bg: "#d8dee8", surface: "#f8fbff", panel: "rgba(255, 255, 255, 0.5)", text: "#151b26", muted: "#5d6879", accent: "#1c2430", accentSoft: "#bcc6d6", line: "rgba(255, 255, 255, 0.6)", shadow: "0 24px 44px rgba(15, 23, 42, 0.1)", buttonText: "#ffffff" },
  cafeWarm: { bg: "#f4ead9", surface: "#fff8ef", panel: "rgba(255, 248, 239, 0.86)", text: "#2b221a", muted: "#6a5c4f", accent: "#5d3b24", accentSoft: "#e8c498", line: "rgba(43, 34, 26, 0.1)", shadow: "0 20px 34px rgba(43, 34, 26, 0.1)", buttonText: "#ffffff" },
};

const route = (slug, label, kind) => ({ slug, label, kind });
const stat = (label, value) => ({ label, value });

const routeKindDescriptions = {
  home: "This is the operating homepage. Build a complete landing surface, not a cover page.",
  browse: "Use a browse or catalog structure with filtering, category anchors, and fast exploration.",
  detail: "Lead with product, room, program, or service depth. Make the decision points obvious.",
  checkout: "Show an intentional conversion flow with options, quantity, summary, and next action.",
  brand: "Present the brand world, trust layer, and operating context rather than generic about text.",
  reserve: "Design around booking or request flow, availability, and frictionless form completion.",
  guide: "Organize operational guidance, visit rules, maps, FAQ, and preparation details clearly.",
  features: "Explain product capabilities through productized modules, diagrams, and proof points.",
  cases: "Focus on real use cases, metrics, teams, outcomes, and before or after patterns.",
  pricing: "Make plans, pricing differences, and commitment decisions easy to compare.",
  contact: "Focus on inquiry, demo request, response expectations, and business trust signals.",
  works: "Treat the page as a project index with filters, featured work, and quick case entry.",
  services: "Frame service scope, deliverables, and process with confidence and specificity.",
  brief: "Design a compact but premium brief intake flow with structured fields and expectations.",
  lineup: "Build the page around talent cards, dates, stages, and discovery rather than prose.",
  schedule: "Make timeline, stage movement, and time slots immediately legible.",
  tickets: "Present ticket classes, pricing, perks, and purchase CTA with low friction.",
  feed: "Create a living activity feed for the community with clear recency and member energy.",
  perks: "Show benefits, exclusive value, and membership depth in a concise visual structure.",
  join: "Focus on membership signup, plan choice, and the reasons to commit today.",
};

const stageHeights = {
  home: { desktop: 1480, mobile: 980 }, browse: { desktop: 1420, mobile: 980 }, detail: { desktop: 1380, mobile: 980 }, checkout: { desktop: 1320, mobile: 940 }, brand: { desktop: 1260, mobile: 920 }, reserve: { desktop: 1320, mobile: 940 }, guide: { desktop: 1220, mobile: 900 }, features: { desktop: 1420, mobile: 980 }, cases: { desktop: 1340, mobile: 940 }, pricing: { desktop: 1260, mobile: 920 }, contact: { desktop: 1180, mobile: 900 }, works: { desktop: 1420, mobile: 980 }, services: { desktop: 1320, mobile: 920 }, brief: { desktop: 1220, mobile: 900 }, lineup: { desktop: 1440, mobile: 980 }, schedule: { desktop: 1300, mobile: 940 }, tickets: { desktop: 1260, mobile: 920 }, feed: { desktop: 1360, mobile: 960 }, perks: { desktop: 1280, mobile: 920 }, join: { desktop: 1240, mobile: 920 },
};

const rawSites = [
  {
    id: "sneaker-drop",
    brand: "RIFT/01",
    industry: "Sneaker Commerce",
    category: "commerce",
    summary: "Limited sneaker commerce with launch countdown and fast cart entry.",
    backdrop: "neo",
    themeKey: "neoSun",
    imageStyle: "neo-brutal",
    homeMode: "Poster drop wall",
    mobileRule: "Put size choice, price, and buy action in the first viewport.",
    hero: { eyebrow: "Limited Drop", title: "Street launch site built around one hot drop at a time.", subtitle: "The first screen should feel like an event release, not a general store hero.", primary: "Open Drop", secondary: "Size Guide" },
    routes: [route("home", "Home", "home"), route("drops", "Drops", "browse"), route("styles", "Styles", "detail"), route("cart", "Cart", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Drop opens", "20:00"), stat("Focus size", "270 mm"), stat("Heat meter", "92%")],
    chips: ["Shock color", "Countdown rail", "Sticker UI"],
    design: { family: "Street launch lab", heroMode: "Poster-led hero with price strip and side countdown.", background: "Big campaign photo with layered panels rising over it.", motion: "Countdown plate and size rail land at different depths.", keywords: ["poster commerce", "drop countdown", "bold sticker UI"] },
  },
  {
    id: "supplement-brand",
    brand: "PUNCH FUEL",
    industry: "Supplement Commerce",
    category: "commerce",
    summary: "DTC supplement brand centered on routine composition and subscription bundles.",
    backdrop: "neo",
    themeKey: "neoSun",
    imageStyle: "neo-brutal",
    homeMode: "Routine builder split",
    mobileRule: "Open with a routine selector, plan price, and subscribe CTA before long explanation.",
    hero: { eyebrow: "Routine Builder", title: "Build a supplement stack around a daily ritual, not a catalog grid.", subtitle: "The homepage should lead with routine assembly and plan outcome.", primary: "Build Stack", secondary: "Compare Plans" },
    routes: [route("home", "Home", "home"), route("routine", "Routine", "browse"), route("compare", "Compare", "detail"), route("subscribe", "Subscribe", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Monthly plan", "39,000원"), stat("Stack slots", "12"), stat("Repeat rate", "68%")],
    chips: ["Routine split", "AM / PM", "Subscription-first"],
    design: { family: "Performance DTC brand", heroMode: "Routine builder on one side, product macro on the other.", background: "Sharp product macro with sporty gradient blocks.", motion: "Routine chips and dosage cards clip onto the canvas in layers.", keywords: ["routine commerce", "stack configurator", "macro product shot"] },
  },
  {
    id: "boxing-gym",
    brand: "UPPERCUT CLUB",
    industry: "Boxing Gym",
    category: "booking",
    summary: "A high-energy boxing gym site where trial booking sits ahead of program browsing.",
    backdrop: "retro",
    themeKey: "ringNight",
    imageStyle: "neo-brutal",
    homeMode: "Booking widget first",
    mobileRule: "Surface the trial schedule, coach snapshot, and join CTA in the first viewport.",
    hero: { eyebrow: "Trial Booking", title: "Enter like a gym floor, then book a slot before you read.", subtitle: "The site should feel immediate, physical, and schedule-led.", primary: "Book Trial", secondary: "Meet Coaches" },
    routes: [route("home", "Home", "home"), route("classes", "Classes", "browse"), route("coaches", "Coaches", "detail"), route("join", "Join", "reserve"), route("guide", "Guide", "guide")],
    stats: [stat("Open rings", "18"), stat("Trial pass", "19,000원"), stat("Member score", "4.9")],
    chips: ["Fight poster", "Schedule card", "Coach badges"],
    design: { family: "Fight club booking", heroMode: "Massive gym photography with floating booking card.", background: "Dark ring photography with neon haze and subtle scan-line mesh.", motion: "Booking card rises over the photo while coach chips land later.", keywords: ["boxing booking", "immersive sports hero", "floating reservation card"] },
  },
  {
    id: "wealth-app",
    brand: "CLARO",
    industry: "Wealth SaaS",
    category: "saas",
    summary: "A personal wealth SaaS focused on dashboard confidence, goal tracking, and portfolio clarity.",
    backdrop: "minimal",
    themeKey: "monoStone",
    imageStyle: "bold-minimal",
    homeMode: "Dashboard bento",
    mobileRule: "Prioritize KPI modules, target progress, and a single conversion path to start.",
    hero: { eyebrow: "Portfolio OS", title: "Open the site into a board of numbers, motion, and financial calm.", subtitle: "The page should look product-first and operator-ready.", primary: "See Features", secondary: "View Pricing" },
    routes: [route("home", "Home", "home"), route("features", "Features", "features"), route("cases", "Cases", "cases"), route("pricing", "Pricing", "pricing"), route("contact", "Contact", "contact")],
    stats: [stat("Monthly plan", "월 39,000원"), stat("Setup time", "7 minutes"), stat("Goal hit", "84%")],
    chips: ["Dashboard first", "Soft grid", "Quiet motion"],
    design: { family: "Quiet finance OS", heroMode: "Dashboard-led first screen with KPI tiles and small charts.", background: "No photo hero. Use responsive mesh gradients and restrained depth.", motion: "Charts and target cards reveal with subtle layered motion.", keywords: ["dashboard SaaS", "quiet finance", "mesh background"] },
  },
  {
    id: "skin-clinic",
    brand: "ATELIER SKIN",
    industry: "Skin Clinic",
    category: "booking",
    summary: "Premium skin clinic with diagnosis-led booking, treatment programs, and medical trust cues.",
    backdrop: "minimal",
    themeKey: "monoClinic",
    imageStyle: "bold-minimal",
    homeMode: "Clinic stack",
    mobileRule: "Pin diagnosis CTA and open consult slots above every editorial section.",
    hero: { eyebrow: "Diagnosis First", title: "Lead with diagnosis and booking, not a generic beauty campaign.", subtitle: "The site should feel like a premium clinic with an active intake flow.", primary: "Start Diagnosis", secondary: "Book Visit" },
    routes: [route("home", "Home", "home"), route("programs", "Programs", "browse"), route("scan", "AI Scan", "detail"), route("booking", "Booking", "reserve"), route("clinic", "Clinic", "guide")],
    stats: [stat("Diagnosis fee", "29,000원"), stat("Consult type", "1:1"), stat("Return rate", "96%")],
    chips: ["Clinic calm", "Intake form", "Doctor trust"],
    design: { family: "Premium clinical booking", heroMode: "Treatment space photo with diagnosis CTA column and open-slot widget.", background: "Large clinic photography with soft shadowed cards floating upward.", motion: "Treatment cards and booking rows appear as layered translucent sheets.", keywords: ["clinic booking", "diagnosis-led", "soft layered panels"] },
  },
  {
    id: "arch-studio",
    brand: "PLAIN GRID",
    industry: "Architecture Studio",
    category: "portfolio",
    summary: "Editorial architecture portfolio that should feel like a real studio commission site.",
    backdrop: "grain",
    themeKey: "studioWarm",
    imageStyle: "bold-minimal",
    homeMode: "Editorial canvas",
    mobileRule: "Mobile should read like a visual brief deck with project cards and inquiry entry.",
    hero: { eyebrow: "Editorial Portfolio", title: "The homepage should behave like a studio issue, not a service funnel.", subtitle: "Lead with imagery, project voice, and commission confidence.", primary: "View Works", secondary: "Send Brief" },
    routes: [route("home", "Home", "home"), route("works", "Works", "works"), route("services", "Services", "services"), route("brief", "Brief", "brief"), route("contact", "Contact", "contact")],
    stats: [stat("Built projects", "32"), stat("Avg lead", "8 weeks"), stat("Focus", "Hospitality")],
    chips: ["Editorial spread", "Serif display", "Project voice"],
    design: { family: "Editorial studio portfolio", heroMode: "Image-led editorial spread with type anchored beside the photo.", background: "Large architecture photography with grain and paper warmth.", motion: "Blocks rise as layered editorial sheets and overlap on scroll.", keywords: ["editorial architecture", "serif portfolio", "image spread"] },
  },
  {
    id: "beauty-flash-sale",
    brand: "MELT POP",
    industry: "Beauty Flash Commerce",
    category: "commerce",
    summary: "High-tempo beauty commerce centered on kits, sale urgency, and palette-led shopping.",
    backdrop: "max",
    themeKey: "popRush",
    imageStyle: "maximal-pop",
    homeMode: "Sale poster board",
    mobileRule: "Show the hero price, kit choice, and checkout path before campaign storytelling.",
    hero: { eyebrow: "48H Flash Sale", title: "Treat the homepage like a glossy sale poster wall with live kit entry.", subtitle: "Everything should feel purchase-ready in the first seconds.", primary: "Shop Kits", secondary: "See Shades" },
    routes: [route("home", "Home", "home"), route("shop", "Shop", "browse"), route("shades", "Shades", "detail"), route("cart", "Cart", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Flash price", "29,900원"), stat("Shade count", "300"), stat("Ends in", "48h")],
    chips: ["Poster sale", "Price stickers", "Gloss texture"],
    design: { family: "Campaign-sale beauty", heroMode: "Poster-style first screen with giant price typography and layered kit cards.", background: "High-gloss campaign imagery with color stickers and overlapping sale tags.", motion: "Sale tags, swatches, and price strips float upward and cross each other.", keywords: ["beauty sale", "poster commerce", "gloss campaign"] },
  },
  {
    id: "festival-page",
    brand: "NOISE WAVE",
    industry: "Festival Event",
    category: "event",
    summary: "Festival site built around lineup discovery, timetable clarity, and ticket purchase.",
    backdrop: "retro",
    themeKey: "signalNight",
    imageStyle: "maximal-pop",
    homeMode: "Festival poster stack",
    mobileRule: "Open directly into lineup highlights, date, and ticket choice instead of long intro copy.",
    hero: { eyebrow: "Festival 2026", title: "The homepage should feel like a live event surface, not a brochure.", subtitle: "The first screen needs lineup signal, time, and ticket path immediately.", primary: "Buy Tickets", secondary: "See Lineup" },
    routes: [route("home", "Home", "home"), route("lineup", "Lineup", "lineup"), route("schedule", "Schedule", "schedule"), route("tickets", "Tickets", "tickets"), route("guide", "Guide", "guide")],
    stats: [stat("Day pass", "119,000원"), stat("Artists", "18"), stat("Gate opens", "14:00")],
    chips: ["Event poster", "Stage timing", "Ticket matrix"],
    design: { family: "Poster event system", heroMode: "Poster-led hero with lineup blocks, date stamp, and immediate ticket CTA.", background: "Large event imagery, spotlight gradients, and neon schedule cues.", motion: "Lineup cards and timing rails stack and rise like layered festival posters.", keywords: ["festival poster", "lineup discovery", "ticket matrix"] },
  },
  {
    id: "creator-club",
    brand: "RALLY HOUSE",
    industry: "Creator Community",
    category: "event",
    summary: "A creator community site with live feed energy, membership perks, and join flow.",
    backdrop: "max",
    themeKey: "popRush",
    imageStyle: "maximal-pop",
    homeMode: "Community live feed",
    mobileRule: "Lead with live updates, pass options, and join entry before community explanation.",
    hero: { eyebrow: "Creator Feed", title: "Open into a living club feed instead of a generic membership landing page.", subtitle: "Make the site feel active right now, with the join path always nearby.", primary: "Join Club", secondary: "View Perks" },
    routes: [route("home", "Home", "home"), route("feed", "Feed", "feed"), route("perks", "Perks", "perks"), route("join", "Join", "join"), route("guide", "Guide", "guide")],
    stats: [stat("Monthly pass", "12,000원"), stat("Live rooms", "48"), stat("Drop nights", "Every week")],
    chips: ["Live feed", "Pass cards", "Aura mesh"],
    design: { family: "Pop community platform", heroMode: "Feed-led first screen with live activity modules and join CTA beside it.", background: "No photo-first hero. Use mesh, aura, and soft physics-driven motion.", motion: "Feed cards and pass labels appear on different depth planes.", keywords: ["community feed", "membership join", "aurora mesh"] },
  },
  {
    id: "ev-mobility",
    brand: "ORBIT E",
    industry: "EV Mobility",
    category: "booking",
    summary: "An EV mobility site centered on model comparison, charge depth, and test-drive booking.",
    backdrop: "retro",
    themeKey: "signalNight",
    imageStyle: "retrofuture",
    homeMode: "Model compare dashboard",
    mobileRule: "Surface compare rows, charge logic, and test-drive CTA without burying them under brand copy.",
    hero: { eyebrow: "Drive Intelligence", title: "Lead with comparison and charge confidence before anything else.", subtitle: "The first screen should feel like a product compare console for real buyers.", primary: "Book Drive", secondary: "Compare Models" },
    routes: [route("home", "Home", "home"), route("models", "Models", "browse"), route("charge", "Charge", "detail"), route("drive", "Drive", "reserve"), route("support", "Support", "guide")],
    stats: [stat("Range", "540 km"), stat("Charge time", "18 min"), stat("Test wait", "12 days")],
    chips: ["Compare table", "Charge logic", "Metallic glow"],
    design: { family: "Future mobility compare", heroMode: "Comparison-led first screen with specs, range badges, and test-drive card visible at once.", background: "Hero vehicle imagery mixed with metallic reflections and responsive mesh depth.", motion: "Spec chips and compare rows glide in with measured technical precision.", keywords: ["EV compare", "test-drive booking", "technical dashboard"] },
  },
  {
    id: "gaming-gear",
    brand: "VOID ARC",
    industry: "Gaming Gear",
    category: "commerce",
    summary: "Gaming hardware commerce organized around setup bundles, specs, and aggressive cart entry.",
    backdrop: "retro",
    themeKey: "signalNight",
    imageStyle: "retrofuture",
    homeMode: "Setup command center",
    mobileRule: "Bring bundle spec, price, and cart action ahead of community or editorial blocks.",
    hero: { eyebrow: "Setup Bundle", title: "Make the homepage feel like a battle station selector, not a simple grid.", subtitle: "Specs and bundle entry should dominate the first screen.", primary: "View Bundles", secondary: "Open Cart" },
    routes: [route("home", "Home", "home"), route("gear", "Gear", "browse"), route("bundle", "Bundle", "detail"), route("cart", "Cart", "checkout"), route("support", "Support", "brand")],
    stats: [stat("Bundle price", "329,000원"), stat("Launch window", "24 hours"), stat("Mouse weight", "1.8g")],
    chips: ["Spec stack", "RGB depth", "Command UI"],
    design: { family: "Setup command commerce", heroMode: "A setup-control first screen with hardware visuals, spec modules, and bundle CTA.", background: "Dark desk setup imagery with RGB atmosphere and reactive line work.", motion: "Spec panels and cart chips animate like a command interface.", keywords: ["gaming setup", "bundle commerce", "spec UI"] },
  },
  {
    id: "ai-saas",
    brand: "SIGNAL GRID",
    industry: "AI Workflow SaaS",
    category: "saas",
    summary: "Workflow automation SaaS structured around flow boards, use cases, and pricing clarity.",
    backdrop: "retro",
    themeKey: "signalNight",
    imageStyle: "retrofuture",
    homeMode: "Workflow board",
    mobileRule: "Foreground workflow states, KPI cards, and a single product CTA instead of shrinking the desktop board.",
    hero: { eyebrow: "Workflow Board", title: "Open into an active AI workflow board instead of a startup headline stack.", subtitle: "Users should understand the product by glancing at the interface first.", primary: "Explore Flows", secondary: "See Pricing" },
    routes: [route("home", "Home", "home"), route("flows", "Flows", "features"), route("cases", "Cases", "cases"), route("pricing", "Pricing", "pricing"), route("contact", "Contact", "contact")],
    stats: [stat("Starter", "월 39,000원"), stat("Saved hours", "128h"), stat("Close rate", "31%")],
    chips: ["Workflow graph", "KPI tiles", "Mesh depth"],
    design: { family: "AI product board", heroMode: "Workflow-board homepage with logic nodes, KPI tiles, and action chips.", background: "Responsive mesh and aura depth rather than stock imagery.", motion: "Node clusters, metric chips, and CTA rails animate at different layers with restraint.", keywords: ["workflow SaaS", "graph board", "technical glow"] },
  },
  {
    id: "indie-bookstore",
    brand: "PAPER NOOK",
    industry: "Independent Bookstore",
    category: "commerce",
    summary: "A curated bookstore site that should feel like an editorial shelf, not a mass retailer.",
    backdrop: "collage",
    themeKey: "paperWarm",
    imageStyle: "collage-paper",
    homeMode: "Shelf editorial",
    mobileRule: "Treat picks, notes, and gift CTA like a magazine deck rather than a compressed grid.",
    hero: { eyebrow: "Curated Shelf", title: "Make the homepage read like a bookseller issue with a living shelf.", subtitle: "The site should feel hand-curated and giftable from the first viewport.", primary: "Browse Shelf", secondary: "Gift Picks" },
    routes: [route("home", "Home", "home"), route("shelf", "Shelf", "browse"), route("picks", "Picks", "detail"), route("gift", "Gift", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Shelf edits", "12"), stat("Gift set", "29,000원"), stat("Weekly notes", "3")],
    chips: ["Paper grain", "Editorial notes", "Shelf stacks"],
    design: { family: "Paper editorial commerce", heroMode: "Shelf-and-note first screen with editorial snippets and gift cues.", background: "Paper texture, torn edges, and warm photography rather than polished commerce blocks.", motion: "Book notes and shelf cards float like clipped paper pieces.", keywords: ["indie bookstore", "editorial shelf", "paper collage"] },
  },
  {
    id: "stationery-shop",
    brand: "CUT & NOTE",
    industry: "Stationery Shop",
    category: "commerce",
    summary: "A stationery commerce site built around kits, palette combinations, and tactile paper detail.",
    backdrop: "collage",
    themeKey: "paperWarm",
    imageStyle: "collage-paper",
    homeMode: "Paper kit board",
    mobileRule: "Prioritize kit composition, color combinations, and basket entry instead of long brand text.",
    hero: { eyebrow: "Paper Kit", title: "The first screen should feel like a desk board of kit pieces and color combinations.", subtitle: "Users should understand the product through arrangement, not explanation.", primary: "Browse Kits", secondary: "Open Basket" },
    routes: [route("home", "Home", "home"), route("kits", "Kits", "browse"), route("colors", "Colors", "detail"), route("basket", "Basket", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Kit price", "34,900원"), stat("Palette sets", "18"), stat("Wrap option", "Available")],
    chips: ["Tactile desk", "Palette board", "Paper overlap"],
    design: { family: "Tactile collage commerce", heroMode: "A board of stationery pieces, taped notes, and visible kit assembly.", background: "Paper material, taped edges, and physical texture with soft motion.", motion: "Items behave like light paper pieces sliding and overlapping.", keywords: ["stationery collage", "tactile commerce", "desk board"] },
  },
  {
    id: "local-cafe",
    brand: "TABLE WARM",
    industry: "Cafe Reservation",
    category: "booking",
    summary: "A cafe site focused on today's menu, seat availability, and direct reservation entry.",
    backdrop: "hand",
    themeKey: "cafeWarm",
    imageStyle: "collage-paper",
    homeMode: "Cafe window",
    mobileRule: "Put today's menu and seat reservation in the first two blocks with no extra ceremony.",
    hero: { eyebrow: "Today at Cafe", title: "Open like a real storefront window with menu and seating already visible.", subtitle: "The site should feel walk-in friendly and alive, not like a lifestyle magazine.", primary: "Reserve Seat", secondary: "See Menu" },
    routes: [route("home", "Home", "home"), route("menu", "Menu", "browse"), route("visit", "Visit", "detail"), route("reserve", "Reserve", "reserve"), route("info", "Info", "guide")],
    stats: [stat("Open seats", "7"), stat("Table hold", "12 min"), stat("Set menu", "18,000원")],
    chips: ["Storefront photo", "Menu board", "Warm notes"],
    design: { family: "Warm storefront booking", heroMode: "Storefront hero with today's menu board and reservation module visible immediately.", background: "Big cafe imagery, paper menu notes, and gentle hand-crafted depth.", motion: "Menu plates and reservation notes lift softly over the storefront image.", keywords: ["cafe reservation", "storefront layout", "menu board"] },
  },
  {
    id: "boutique-hotel",
    brand: "HOTEL STILL",
    industry: "Boutique Hotel",
    category: "booking",
    summary: "A boutique hotel site driven by room imagery, stay finder, and package selection.",
    backdrop: "grain",
    themeKey: "grainStone",
    imageStyle: "grain-editorial",
    homeMode: "Stay finder hero",
    mobileRule: "Show the room photo first but keep the stay finder and offer CTA immediately attached to it.",
    hero: { eyebrow: "Stay Finder", title: "The site should feel like a real hotel homepage with booking intent from frame one.", subtitle: "Room imagery and reservation control need to coexist in the opening view.", primary: "Book Stay", secondary: "See Rooms" },
    routes: [route("home", "Home", "home"), route("rooms", "Rooms", "browse"), route("offers", "Offers", "detail"), route("booking", "Booking", "reserve"), route("guide", "Guide", "guide")],
    stats: [stat("Night rate", "189,000원"), stat("Check-in", "15:00"), stat("Packages", "4")],
    chips: ["Full-bleed photo", "Stay finder", "Package cards"],
    design: { family: "Boutique stay booking", heroMode: "Large room photography with the stay finder layered directly on top.", background: "High-resolution room imagery and floating blocks that rise over the photo on scroll.", motion: "Package cards and room details reveal as overlapping sheets.", keywords: ["hotel booking", "room image first", "floating stay finder"] },
  },
  {
    id: "perfume-house",
    brand: "MOSS & AMBER",
    industry: "Perfume House",
    category: "commerce",
    summary: "A perfume site built around mood imagery, note structure, and curated set purchase.",
    backdrop: "grain",
    themeKey: "grainStone",
    imageStyle: "grain-editorial",
    homeMode: "Scent mood film",
    mobileRule: "Turn notes, set price, and gift CTA into touch-ready cards instead of shrinking a mood canvas.",
    hero: { eyebrow: "Scent Mood", title: "Treat the homepage like a perfume editorial with note cards and set entry.", subtitle: "The first screen should feel atmospheric but still commercially legible.", primary: "Browse Sets", secondary: "Gift Select" },
    routes: [route("home", "Home", "home"), route("sets", "Sets", "browse"), route("notes", "Notes", "detail"), route("gift", "Gift", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Set price", "74,000원"), stat("Core notes", "21"), stat("Gift wrap", "Included")],
    chips: ["Mood film", "Note cards", "Gift path"],
    design: { family: "Mood-led perfume house", heroMode: "Editorial mood canvas with layered note cards and direct set entry.", background: "Cinematic fragrance visuals with soft blur, depth, and quiet layered reveals.", motion: "Note cards and scent descriptors drift in layered motion over the hero visual.", keywords: ["perfume editorial", "note cards", "mood commerce"] },
  },
  {
    id: "furniture-store",
    brand: "MOSS HOME",
    industry: "Furniture Commerce",
    category: "commerce",
    summary: "A furniture site centered on room planning, bundle shopping, and spatial exploration.",
    backdrop: "organic",
    themeKey: "organicSoft",
    imageStyle: "organic-soft",
    homeMode: "Room planner",
    mobileRule: "Surface room choices and planner CTA as the main behavior, not as secondary footer content.",
    hero: { eyebrow: "Room Planner", title: "Open with a room-planning surface instead of a standard product hero.", subtitle: "The first screen should let users choose a room mood immediately.", primary: "Plan Room", secondary: "View Bundle" },
    routes: [route("home", "Home", "home"), route("rooms", "Rooms", "browse"), route("planner", "Planner", "detail"), route("cart", "Cart", "checkout"), route("service", "Service", "brand")],
    stats: [stat("Bundle options", "12"), stat("Lead time", "3 weeks"), stat("Room sets", "9")],
    chips: ["Room mood", "Planner CTA", "Organic depth"],
    design: { family: "Spatial planning commerce", heroMode: "Room planner-led homepage with room selectors and bundle CTA visible immediately.", background: "Large interior imagery, soft organic gradients, and layered planner panels.", motion: "Room tags and planner cards float in like layout sheets.", keywords: ["furniture planner", "room-based commerce", "organic depth"] },
  },
  {
    id: "youth-fashion",
    brand: "BOP BOP",
    industry: "Youth Fashion",
    category: "commerce",
    summary: "A youth fashion site built as a lookbook rail with strong image sequencing and fast shop entry.",
    backdrop: "playful",
    themeKey: "playBright",
    imageStyle: "playful-type",
    homeMode: "Lookbook rail",
    mobileRule: "Transform the lookbook into swipeable outfit stacks with a direct shop CTA on each block.",
    hero: { eyebrow: "Lookbook Rail", title: "Open into a lookbook strip, not a generic apparel storefront.", subtitle: "Outfit imagery and shop entry should feel linked from the first frame.", primary: "Shop Looks", secondary: "Open Cart" },
    routes: [route("home", "Home", "home"), route("looks", "Looks", "browse"), route("shop", "Shop", "detail"), route("cart", "Cart", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Size range", "XS-XL"), stat("Drop sale", "15%"), stat("Entry price", "59,000원+")],
    chips: ["Lookbook rail", "Type-forward", "Youth motion"],
    design: { family: "Lookbook commerce", heroMode: "Lookbook-led hero where images and shop CTAs live in the same visual rail.", background: "Campaign imagery, bright typography, and playful layers rather than minimalist white space.", motion: "Looks and tags glide like a fast-moving editorial rail.", keywords: ["lookbook fashion", "type-led commerce", "image rail"] },
  },
  {
    id: "jewelry-brand",
    brand: "LUNE FORM",
    industry: "Jewelry Brand",
    category: "commerce",
    summary: "A jewelry site structured around collection reveals, bespoke inquiry, and gallery-level image treatment.",
    backdrop: "chrome",
    themeKey: "chromePearl",
    imageStyle: "chrome-luxe",
    homeMode: "Collection gallery",
    mobileRule: "Convert the collection view into clean stacked cards with direct bespoke and consult entry.",
    hero: { eyebrow: "Collection House", title: "Present the homepage like a collection gallery with conversion built into the experience.", subtitle: "Collection reveal and bespoke inquiry should feel equally intentional.", primary: "View Collection", secondary: "Book Consult" },
    routes: [route("home", "Home", "home"), route("collection", "Collection", "browse"), route("bespoke", "Bespoke", "detail"), route("consult", "Consult", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Entry piece", "129,000원"), stat("Consult type", "Private"), stat("Lead time", "2 weeks")],
    chips: ["Gallery reveal", "Macro product", "Metal sheen"],
    design: { family: "Collection gallery commerce", heroMode: "Gallery-led hero with macro product imagery and a clean consult CTA block.", background: "High-resolution jewelry imagery, chrome reflections, and soft physical depth.", motion: "Collection panels and consult cards rise with subtle metallic sheen.", keywords: ["jewelry gallery", "macro product", "bespoke consult"] },
  },
];

export const siteCatalog = rawSites.map((site) => ({
  ...site,
  theme: themes[site.themeKey],
  images: {
    brand: buildImage(site.imageStyle, site.id, "brand"),
    product: buildImage(site.imageStyle, site.id, "product"),
    scene: buildImage(site.imageStyle, site.id, "scene"),
  },
}));

export const siteCatalogById = Object.fromEntries(siteCatalog.map((site) => [site.id, site]));

export function getSiteCatalogEntry(siteId) {
  return siteCatalogById[siteId] ?? null;
}

export function getRoutesForSite(siteId) {
  return getSiteCatalogEntry(siteId)?.routes ?? [route("home", "Home", "home")];
}

export function getBlueprintForSite(siteId) {
  return getSiteCatalogEntry(siteId)?.design ?? {
    family: "Independent digital brand",
    heroMode: "First screen should immediately explain the service without a generic hero stack.",
    background: "Use either a high-resolution image world or a restrained responsive mesh background.",
    motion: "Use layered reveals with depth, but keep the content readable.",
    keywords: ["independent website", "non-template layout"],
  };
}

export function getRouteDescription(kind) {
  return routeKindDescriptions[kind] ?? "Design the page like a real operating page with direct user action.";
}

export function getStageHeight(kind, device) {
  return stageHeights[kind]?.[device] ?? (device === "mobile" ? 940 : 1320);
}
