import { withBasePath } from "../lib/appPaths.js";

const buildImage = (style, siteId, kind) => withBasePath(`/generated/pages/${style}--${siteId}--${kind}.png`);
const buildImageV2 = (siteId, kind) => withBasePath(`/generated/pages-v2/${siteId}-${kind}.png`);

const themes = {
  neoSun: { bg: "#f7e45d", surface: "#fffdf4", panel: "rgba(255, 252, 241, 0.84)", text: "#121212", muted: "#5d5649", accent: "#ff6b6b", accentSoft: "#7dd3fc", line: "rgba(18, 18, 18, 0.16)", shadow: "10px 10px 0 rgba(18, 18, 18, 0.88)", buttonText: "#121212" },
  monoStone: { bg: "#f3f0e8", surface: "#ffffff", panel: "rgba(255, 255, 255, 0.86)", text: "#101828", muted: "#667085", accent: "#111827", accentSoft: "#e7ebf0", line: "rgba(17, 24, 39, 0.08)", shadow: "0 22px 46px rgba(15, 23, 42, 0.1)", buttonText: "#ffffff" },
  monoClinic: { bg: "#f5f3ef", surface: "#ffffff", panel: "rgba(255, 255, 255, 0.9)", text: "#161b26", muted: "#6c7689", accent: "#1d2939", accentSoft: "#d5dde8", line: "rgba(22, 27, 38, 0.08)", shadow: "0 22px 46px rgba(15, 23, 42, 0.08)", buttonText: "#ffffff" },
  studioWarm: { bg: "#efe9df", surface: "#fcf9f5", panel: "rgba(252, 249, 245, 0.88)", text: "#221d18", muted: "#65594b", accent: "#2e241c", accentSoft: "#d9ccb8", line: "rgba(34, 29, 24, 0.12)", shadow: "0 22px 46px rgba(34, 29, 24, 0.1)", buttonText: "#ffffff" },
  popRush: { bg: "#221537", surface: "#2d1b46", panel: "rgba(255, 255, 255, 0.12)", text: "#ffffff", muted: "rgba(255, 255, 255, 0.74)", accent: "#ffd84d", accentSoft: "#ff7ccf", line: "rgba(255, 255, 255, 0.16)", shadow: "0 28px 60px rgba(10, 8, 20, 0.35)", buttonText: "#111111" },
  signalNight: { bg: "#07101d", surface: "#0e1b33", panel: "rgba(10, 22, 42, 0.82)", text: "#ecfbff", muted: "rgba(203, 241, 255, 0.76)", accent: "#39d5ff", accentSoft: "#ff6fe4", line: "rgba(57, 213, 255, 0.18)", shadow: "0 0 42px rgba(57, 213, 255, 0.1)", buttonText: "#071018" },
  ringNight: { bg: "#0b0b12", surface: "#151520", panel: "rgba(18, 18, 28, 0.84)", text: "#f5f7fb", muted: "rgba(225, 232, 244, 0.72)", accent: "#ff6b6b", accentSoft: "#8b5cf6", line: "rgba(255, 255, 255, 0.1)", shadow: "0 28px 64px rgba(4, 4, 10, 0.46)", buttonText: "#111111" },
  paperWarm: { bg: "#f7f1e6", surface: "#fffaf2", panel: "rgba(255, 250, 242, 0.9)", text: "#231d17", muted: "#6d6154", accent: "#f5c24f", accentSoft: "#9fd7f6", line: "rgba(35, 29, 23, 0.1)", shadow: "0 18px 34px rgba(35, 29, 23, 0.12)", buttonText: "#231d17" },
  grainStone: { bg: "#e8ddd0", surface: "#f8f2ea", panel: "rgba(248, 242, 234, 0.84)", text: "#2c231d", muted: "#6b5f53", accent: "#3c2c20", accentSoft: "#d6c3b2", line: "rgba(44, 35, 29, 0.12)", shadow: "0 18px 36px rgba(44, 35, 29, 0.1)", buttonText: "#ffffff" },
  organicSoft: { bg: "#eef5e7", surface: "#f9fcf4", panel: "rgba(249, 252, 244, 0.84)", text: "#23301f", muted: "#55674f", accent: "#24311f", accentSoft: "#cfe6bf", line: "rgba(35, 48, 31, 0.1)", shadow: "0 18px 36px rgba(35, 48, 31, 0.08)", buttonText: "#ffffff" },
  playBright: { bg: "#fff2a9", surface: "#fff8d3", panel: "rgba(255, 248, 211, 0.84)", text: "#121212", muted: "#4f4b43", accent: "#0f3bd9", accentSoft: "#ff79b0", line: "rgba(18, 18, 18, 0.12)", shadow: "0 20px 34px rgba(18, 18, 18, 0.14)", buttonText: "#ffffff" },
  chromePearl: { bg: "#d8dee8", surface: "#f8fbff", panel: "rgba(255, 255, 255, 0.5)", text: "#151b26", muted: "#5d6879", accent: "#1c2430", accentSoft: "#bcc6d6", line: "rgba(255, 255, 255, 0.6)", shadow: "0 24px 44px rgba(15, 23, 42, 0.1)", buttonText: "#ffffff" },
  cafeWarm: { bg: "#f4ead9", surface: "#fff8ef", panel: "rgba(255, 248, 239, 0.86)", text: "#2b221a", muted: "#6a5c4f", accent: "#5d3b24", accentSoft: "#e8c498", line: "rgba(43, 34, 26, 0.1)", shadow: "0 20px 34px rgba(43, 34, 26, 0.1)", buttonText: "#ffffff" },
};

const routeLabels = {
  home: "홈",
  drops: "드롭",
  styles: "스타일",
  cart: "장바구니",
  brand: "브랜드",
  routine: "루틴",
  compare: "비교",
  subscribe: "구독",
  classes: "프로그램",
  coaches: "코치",
  join: "가입",
  guide: "안내",
  features: "기능",
  cases: "사례",
  pricing: "요금",
  contact: "문의",
  programs: "프로그램",
  scan: "AI 진단",
  booking: "예약",
  clinic: "클리닉",
  works: "프로젝트",
  services: "서비스",
  brief: "브리프",
  shop: "쇼핑",
  shades: "컬러",
  lineup: "라인업",
  schedule: "시간표",
  tickets: "티켓",
  feed: "피드",
  perks: "혜택",
  models: "모델",
  charge: "충전",
  drive: "시승",
  gear: "장비",
  bundle: "번들",
  support: "안내",
  flows: "플로우",
  shelf: "서가",
  picks: "추천",
  gift: "선물",
  kits: "키트",
  colors: "컬러",
  menu: "메뉴",
  visit: "방문",
  reserve: "예약",
  info: "정보",
  rooms: "객실",
  offers: "오퍼",
  sets: "세트",
  notes: "노트",
  planner: "플래너",
  service: "서비스",
  looks: "룩북",
  collection: "컬렉션",
  bespoke: "비스포크",
  consult: "상담",
};

const localizedSites = {
  "sneaker-drop": {
    industry: "스니커 커머스",
    summary: "한 번에 하나의 핵심 드롭에 집중하는 한정판 스니커 커머스 사이트.",
    homeMode: "포스터 드롭 월",
    mobileRule: "첫 화면에서 사이즈 선택, 가격, 구매 버튼이 바로 보여야 한다.",
  },
  "supplement-brand": {
    industry: "영양제 커머스",
    summary: "루틴 조합과 정기구독 번들을 중심으로 설계된 D2C 영양제 사이트.",
    homeMode: "루틴 빌더 스플릿",
    mobileRule: "긴 설명보다 루틴 선택, 플랜 가격, 구독 CTA를 먼저 보여준다.",
  },
  "boxing-gym": {
    industry: "복싱짐 예약",
    summary: "프로그램 소개보다 체험 예약이 먼저 열리는 고밀도 복싱짐 사이트.",
    homeMode: "예약 위젯 선행형",
    mobileRule: "첫 화면에 체험 일정, 코치 요약, 등록 CTA가 함께 보여야 한다.",
  },
  "wealth-app": {
    industry: "자산관리 SaaS",
    summary: "목표 추적과 포트폴리오 가시성을 대시보드 중심으로 보여주는 자산관리 SaaS.",
    homeMode: "대시보드 벤토",
    mobileRule: "모바일 첫 화면에서 KPI, 목표 진행률, 시작 CTA를 우선 노출한다.",
  },
  "skin-clinic": {
    industry: "스킨 클리닉 예약",
    summary: "진단형 예약과 시술 프로그램, 의료 신뢰 요소를 함께 보여주는 프리미엄 클리닉 사이트.",
    homeMode: "클리닉 스택",
    mobileRule: "모든 에디토리얼 섹션보다 진단 CTA와 예약 슬롯을 먼저 고정한다.",
  },
  "arch-studio": {
    industry: "건축 스튜디오",
    summary: "실제 건축 스튜디오 의뢰 사이트처럼 보이도록 구성한 에디토리얼 포트폴리오.",
    homeMode: "에디토리얼 캔버스",
    mobileRule: "모바일은 프로젝트 카드와 문의 진입이 먼저 보이는 비주얼 브리프 덱처럼 설계한다.",
  },
  "beauty-flash-sale": {
    industry: "뷰티 플래시 세일",
    summary: "키트 구매, 세일 긴급감, 컬러 탐색을 빠르게 연결하는 고속 뷰티 커머스 사이트.",
    homeMode: "세일 포스터 보드",
    mobileRule: "캠페인 설명보다 히어로 가격, 키트 선택, 결제 경로를 먼저 보여준다.",
  },
  "festival-page": {
    industry: "페스티벌 이벤트",
    summary: "라인업 탐색, 시간표 가독성, 티켓 구매가 바로 이어지는 페스티벌 사이트.",
    homeMode: "페스티벌 포스터 스택",
    mobileRule: "긴 소개문 없이 라인업 하이라이트, 날짜, 티켓 선택이 바로 보여야 한다.",
  },
  "creator-club": {
    industry: "크리에이터 커뮤니티",
    summary: "실시간 활동감, 멤버십 혜택, 가입 흐름을 한 화면 안에서 느끼게 하는 커뮤니티 사이트.",
    homeMode: "커뮤니티 라이브 피드",
    mobileRule: "커뮤니티 설명보다 실시간 업데이트, 패스 옵션, 가입 진입을 먼저 보여준다.",
  },
  "ev-mobility": {
    industry: "EV 모빌리티",
    summary: "모델 비교, 충전 정보, 시승 예약을 제품 콘솔처럼 보여주는 EV 사이트.",
    homeMode: "모델 비교 대시보드",
    mobileRule: "브랜드 카피보다 비교표, 충전 정보, 시승 CTA가 먼저 나와야 한다.",
  },
  "gaming-gear": {
    industry: "게이밍 기어",
    summary: "번들 스펙과 빠른 장바구니 진입을 중심으로 구성한 게이밍 하드웨어 커머스 사이트.",
    homeMode: "셋업 커맨드 센터",
    mobileRule: "커뮤니티나 브랜드 설명보다 번들 스펙, 가격, 구매 버튼을 먼저 노출한다.",
  },
  "ai-saas": {
    industry: "AI 워크플로 SaaS",
    summary: "플로우 보드, 활용 사례, 요금 비교가 한 흐름으로 이어지는 워크플로 자동화 SaaS.",
    homeMode: "워크플로 보드",
    mobileRule: "데스크톱 보드를 줄이지 말고 상태 카드, KPI, 주 CTA를 모바일 전용 순서로 재배치한다.",
  },
  "indie-bookstore": {
    industry: "독립 서점",
    summary: "대형 서점이 아니라 큐레이션 서가처럼 느껴지는 에디토리얼 서점 사이트.",
    homeMode: "서가 에디토리얼",
    mobileRule: "선정 도서와 선물 CTA를 압축 그리드가 아니라 잡지형 카드 흐름으로 보여준다.",
  },
  "stationery-shop": {
    industry: "문구점",
    summary: "키트 조합, 색상 팔레트, 종이 질감을 중심으로 구성한 문구 커머스 사이트.",
    homeMode: "페이퍼 키트 보드",
    mobileRule: "긴 브랜드 설명보다 키트 구성, 컬러 조합, 장바구니 진입을 먼저 보여준다.",
  },
  "local-cafe": {
    industry: "카페 예약",
    summary: "오늘의 메뉴와 좌석 현황, 예약 진입이 실제 매장처럼 바로 보이는 카페 사이트.",
    homeMode: "카페 윈도우",
    mobileRule: "첫 두 블록 안에서 오늘의 메뉴와 좌석 예약을 바로 처리할 수 있어야 한다.",
  },
  "boutique-hotel": {
    industry: "부티크 호텔",
    summary: "객실 이미지와 예약 위젯이 동시에 열리는 실제 운영형 호텔 사이트.",
    homeMode: "스테이 파인더 히어로",
    mobileRule: "객실 사진 아래로 예약 위젯과 오퍼 CTA가 바로 이어져야 한다.",
  },
  "perfume-house": {
    industry: "퍼퓸 하우스",
    summary: "향 노트와 세트 구매를 에디토리얼 무드 속에서 이해하게 하는 향수 사이트.",
    homeMode: "센트 무드 필름",
    mobileRule: "무드 캔버스를 줄이지 말고 노트 카드, 세트 가격, 선물 CTA를 터치형 카드로 재구성한다.",
  },
  "furniture-store": {
    industry: "가구 커머스",
    summary: "공간 선택과 번들 쇼핑을 룸 플래너처럼 다루는 가구 커머스 사이트.",
    homeMode: "룸 플래너",
    mobileRule: "브랜드 스토리보다 공간 선택과 플래너 CTA를 핵심 동작으로 먼저 보여준다.",
  },
  "youth-fashion": {
    industry: "영 패션",
    summary: "룩북 흐름과 빠른 쇼핑 진입이 연결된 이미지 중심 패션 사이트.",
    homeMode: "룩북 레일",
    mobileRule: "룩북을 단순 축소하지 않고 룩 단위 스와이프 카드와 구매 CTA로 재구성한다.",
  },
  "jewelry-brand": {
    industry: "주얼리 브랜드",
    summary: "컬렉션 공개와 상담 전환을 동시에 다루는 갤러리형 주얼리 사이트.",
    homeMode: "컬렉션 갤러리",
    mobileRule: "컬렉션 이미지를 깔끔한 스택 카드로 바꾸고 상담 진입을 바로 붙인다.",
  },
};

const statLabels = {
  "Drop opens": "드롭 오픈",
  "Focus size": "주력 사이즈",
  "Heat meter": "인기 지수",
  "Monthly plan": "월간 플랜",
  "Stack slots": "스택 슬롯",
  "Repeat rate": "재구매율",
  "Open rings": "오픈 링",
  "Trial pass": "체험 패스",
  "Member score": "회원 평점",
  "Setup time": "설정 시간",
  "Goal hit": "목표 달성",
  "Diagnosis fee": "진단 비용",
  "Consult type": "상담 방식",
  "Return rate": "재방문율",
  "Built projects": "완료 프로젝트",
  "Avg lead": "평균 리드",
  Focus: "주력 분야",
  "Flash price": "플래시 특가",
  "Shade count": "컬러 수",
  "Ends in": "종료까지",
  "Day pass": "일일권",
  Artists: "아티스트",
  "Gate opens": "입장 시작",
  "Monthly pass": "월간 패스",
  "Live rooms": "라이브 룸",
  "Drop nights": "드롭 나이트",
  Range: "주행 거리",
  "Charge time": "충전 시간",
  "Test wait": "시승 대기",
  "Bundle price": "번들 가격",
  "Launch window": "출시 기간",
  "Mouse weight": "마우스 무게",
  Starter: "스타터",
  "Saved hours": "절감 시간",
  "Close rate": "전환율",
  "Shelf edits": "큐레이션 선반",
  "Gift set": "선물 세트",
  "Weekly notes": "주간 노트",
  "Kit price": "키트 가격",
  "Palette sets": "팔레트 세트",
  "Wrap option": "포장 옵션",
  "Open seats": "남은 좌석",
  "Table hold": "좌석 홀드",
  "Set menu": "세트 메뉴",
  "Night rate": "1박 요금",
  "Check-in": "체크인",
  Packages: "패키지",
  "Set price": "세트 가격",
  "Core notes": "핵심 노트",
  "Gift wrap": "선물 포장",
  "Bundle options": "번들 옵션",
  "Lead time": "리드 타임",
  "Room sets": "공간 세트",
  "Size range": "사이즈",
  "Drop sale": "드롭 세일",
  "Entry price": "시작가",
  "Entry piece": "입문 가격",
};

const route = (slug, label, kind) => ({ slug, label: routeLabels[slug] ?? label, kind, legacyLabel: label });
const stat = (label, value) => ({ label, value });

const routeKindDescriptions = {
  home: "운영형 홈페이지처럼 설계한다. 커버 페이지가 아니라 실제 사용 흐름이 바로 보여야 한다.",
  browse: "필터, 카테고리, 빠른 탐색이 가능한 목록형 구조로 설계한다.",
  detail: "상품, 객실, 프로그램, 서비스의 핵심 판단 정보가 첫 화면에서 보여야 한다.",
  checkout: "옵션, 수량, 요약, 다음 행동이 선명한 전환형 페이지로 만든다.",
  brand: "흔한 소개문이 아니라 브랜드 세계관과 신뢰 근거가 드러나야 한다.",
  reserve: "예약 흐름, 가능 시간, 선택 옵션, 신청 행동이 위쪽에서 바로 보여야 한다.",
  guide: "방문 안내, 규칙, FAQ, 맵, 준비 사항을 스캔하기 쉽게 정리한다.",
  features: "기능은 제품 모듈, 다이어그램, 흐름 단위로 설명한다.",
  cases: "실제 활용 사례, 성과 수치, 팀 맥락, 전후 비교를 중심으로 보여준다.",
  pricing: "플랜 차이와 선택 기준이 바로 비교되도록 만든다.",
  contact: "문의 흐름, 응답 기대치, 신뢰 요소가 함께 보이는 고신뢰 문의 페이지로 만든다.",
  works: "프로젝트 인덱스와 큐레이션 구조가 분명한 포트폴리오 페이지로 만든다.",
  services: "서비스 범위, 산출물, 진행 방식이 자신 있게 보이도록 설계한다.",
  brief: "고급스럽지만 간결한 브리프 접수 흐름과 구조화된 입력 필드를 만든다.",
  lineup: "긴 설명보다 출연진 카드, 날짜, 무대 정보 중심으로 설계한다.",
  schedule: "시간대, 동선, 핵심 슬롯이 즉시 읽히는 시간표 구조를 만든다.",
  tickets: "티켓 등급, 가격, 혜택, 구매 CTA가 빠르게 이해되어야 한다.",
  feed: "지금 움직이는 커뮤니티처럼 느껴지는 활동 피드 구조를 만든다.",
  perks: "멤버십 가치와 독점 혜택을 짧고 강하게 보여준다.",
  join: "가입 이유, 플랜 선택, 오늘 행동해야 하는 이유가 선명해야 한다.",
};

const stageHeights = {
  home: { desktop: 1480, mobile: 980 }, browse: { desktop: 1420, mobile: 980 }, detail: { desktop: 1380, mobile: 980 }, checkout: { desktop: 1320, mobile: 940 }, brand: { desktop: 1260, mobile: 920 }, reserve: { desktop: 1320, mobile: 940 }, guide: { desktop: 1220, mobile: 900 }, features: { desktop: 1420, mobile: 980 }, cases: { desktop: 1340, mobile: 940 }, pricing: { desktop: 1260, mobile: 920 }, contact: { desktop: 1180, mobile: 900 }, works: { desktop: 1420, mobile: 980 }, services: { desktop: 1320, mobile: 920 }, brief: { desktop: 1220, mobile: 900 }, lineup: { desktop: 1440, mobile: 980 }, schedule: { desktop: 1300, mobile: 940 }, tickets: { desktop: 1260, mobile: 920 }, feed: { desktop: 1360, mobile: 960 }, perks: { desktop: 1280, mobile: 920 }, join: { desktop: 1240, mobile: 920 },
};

const motionPresets = {
  "sneaker-drop": { profile: "poster-split", layout: "poster", homeVariant: "drop-poster-wall", homeExperience: "dynamic-launch", tempo: "fast" },
  "supplement-brand": { profile: "routine-stack", layout: "commerce", homeVariant: "routine-product-stack", homeExperience: "retail-browse", tempo: "medium" },
  "boxing-gym": { profile: "kinetic-ring", layout: "booking", homeVariant: "fight-schedule-split", homeExperience: "kinetic-split", tempo: "fast" },
  "wealth-app": { profile: "data-constellation", layout: "dashboard", homeVariant: "wealth-command-grid", homeExperience: "business-clean", tempo: "slow" },
  "skin-clinic": { profile: "clinical-layers", layout: "clinic", homeVariant: "clinic-appointment-clean", homeExperience: "beauty-counter", tempo: "slow" },
  "arch-studio": { profile: "editorial-sheets", layout: "editorial", homeVariant: "architecture-editorial-spread", homeExperience: "editorial-magazine", tempo: "slow" },
  "beauty-flash-sale": { profile: "sale-burst", layout: "sale", homeVariant: "beauty-flash-ticker", homeExperience: "flash-sale", tempo: "fast" },
  "festival-page": { profile: "poster-stage", layout: "event", homeVariant: "festival-lineup-poster", homeExperience: "poster-world", tempo: "fast" },
  "creator-club": { profile: "live-feed", layout: "community", homeVariant: "creator-live-feed", homeExperience: "live-feed", tempo: "medium" },
  "ev-mobility": { profile: "charge-console", layout: "mobility", homeVariant: "ev-route-console", homeExperience: "tech-console", tempo: "medium" },
  "gaming-gear": { profile: "command-center", layout: "command", homeVariant: "gaming-loadout-hud", homeExperience: "gaming-hud", tempo: "fast" },
  "ai-saas": { profile: "workflow-map", layout: "dashboard", homeVariant: "ai-workflow-map", homeExperience: "workflow-map", tempo: "slow" },
  "indie-bookstore": { profile: "paper-shelf", layout: "paper", homeVariant: "bookstore-shelf-curation", homeExperience: "quiet-catalog", tempo: "slow" },
  "stationery-shop": { profile: "paper-kit", layout: "paper", homeVariant: "stationery-kit-swatch", homeExperience: "kit-table", tempo: "slow" },
  "local-cafe": { profile: "storefront-window", layout: "storefront", homeVariant: "cafe-menu-window", homeExperience: "storefront-window", tempo: "slow" },
  "boutique-hotel": { profile: "stay-film", layout: "stay", homeVariant: "hotel-stay-finder", homeExperience: "luxury-lounge", tempo: "slow" },
  "perfume-house": { profile: "scent-film", layout: "scent", homeVariant: "perfume-note-film", homeExperience: "minimal-statement", tempo: "slow" },
  "furniture-store": { profile: "room-planner", layout: "room", homeVariant: "furniture-room-planner", homeExperience: "showroom-planner", tempo: "slow" },
  "youth-fashion": { profile: "lookbook-rail", layout: "lookbook", homeVariant: "fashion-lookbook-rail", homeExperience: "lookbook-rail", tempo: "fast" },
  "jewelry-brand": { profile: "gallery-reveal", layout: "gallery", homeVariant: "jewelry-gallery-focus", homeExperience: "gallery-focus", tempo: "slow" },
};

const rawSites = [
  {
    id: "sneaker-drop",
    brand: "RIFT/01",
    industry: "Sneaker Commerce",
    category: "commerce",
    summary: "Limited sneaker commerce with launch countdown and fast cart entry.",
    backdrop: "neo",
    themeKey: "neoSun",
    imageStyle: "neo-brutal",
    homeMode: "Poster drop wall",
    mobileRule: "Put size choice, price, and buy action in the first viewport.",
    hero: { eyebrow: "Limited Drop", title: "Street launch site built around one hot drop at a time.", subtitle: "The first screen should feel like an event release, not a general store hero.", primary: "Open Drop", secondary: "Size Guide" },
    routes: [route("home", "Home", "home"), route("drops", "Drops", "browse"), route("styles", "Styles", "detail"), route("cart", "Cart", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Drop opens", "20:00"), stat("Focus size", "270 mm"), stat("Heat meter", "92%")],
    chips: ["Shock color", "Countdown rail", "Sticker UI"],
    design: { family: "Street launch lab", heroMode: "Poster-led hero with price strip and side countdown.", background: "Big campaign photo with layered panels rising over it.", motion: "Countdown plate and size rail land at different depths.", keywords: ["poster commerce", "drop countdown", "bold sticker UI"] },
  },
  {
    id: "supplement-brand",
    brand: "PUNCH FUEL",
    industry: "Supplement Commerce",
    category: "commerce",
    summary: "DTC supplement brand centered on routine composition and subscription bundles.",
    backdrop: "neo",
    themeKey: "neoSun",
    imageStyle: "neo-brutal",
    homeMode: "Routine builder split",
    mobileRule: "Open with a routine selector, plan price, and subscribe CTA before long explanation.",
    hero: { eyebrow: "Routine Builder", title: "Build a supplement stack around a daily ritual, not a catalog grid.", subtitle: "The homepage should lead with routine assembly and plan outcome.", primary: "Build Stack", secondary: "Compare Plans" },
    routes: [route("home", "Home", "home"), route("routine", "Routine", "browse"), route("compare", "Compare", "detail"), route("subscribe", "Subscribe", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Monthly plan", "39,000원"), stat("Stack slots", "12"), stat("Repeat rate", "68%")],
    chips: ["Routine split", "AM / PM", "Subscription-first"],
    design: { family: "Performance DTC brand", heroMode: "Routine builder on one side, product macro on the other.", background: "Sharp product macro with sporty gradient blocks.", motion: "Routine chips and dosage cards clip onto the canvas in layers.", keywords: ["routine commerce", "stack configurator", "macro product shot"] },
  },
  {
    id: "boxing-gym",
    brand: "UPPERCUT CLUB",
    industry: "Boxing Gym",
    category: "booking",
    summary: "A high-energy boxing gym site where trial booking sits ahead of program browsing.",
    backdrop: "retro",
    themeKey: "ringNight",
    imageStyle: "neo-brutal",
    homeMode: "Booking widget first",
    mobileRule: "Surface the trial schedule, coach snapshot, and join CTA in the first viewport.",
    hero: { eyebrow: "Trial Booking", title: "Enter like a gym floor, then book a slot before you read.", subtitle: "The site should feel immediate, physical, and schedule-led.", primary: "Book Trial", secondary: "Meet Coaches" },
    routes: [route("home", "Home", "home"), route("classes", "Classes", "browse"), route("coaches", "Coaches", "detail"), route("join", "Join", "reserve"), route("guide", "Guide", "guide")],
    stats: [stat("Open rings", "18"), stat("Trial pass", "19,000원"), stat("Member score", "4.9")],
    chips: ["Fight poster", "Schedule card", "Coach badges"],
    design: { family: "Fight club booking", heroMode: "Massive gym photography with floating booking card.", background: "Dark ring photography with neon haze and subtle scan-line mesh.", motion: "Booking card rises over the photo while coach chips land later.", keywords: ["boxing booking", "immersive sports hero", "floating reservation card"] },
  },
  {
    id: "wealth-app",
    brand: "CLARO",
    industry: "Wealth SaaS",
    category: "saas",
    summary: "A personal wealth SaaS focused on dashboard confidence, goal tracking, and portfolio clarity.",
    backdrop: "minimal",
    themeKey: "monoStone",
    imageStyle: "bold-minimal",
    homeMode: "Dashboard bento",
    mobileRule: "Prioritize KPI modules, target progress, and a single conversion path to start.",
    hero: { eyebrow: "Portfolio OS", title: "Open the site into a board of numbers, motion, and financial calm.", subtitle: "The page should look product-first and operator-ready.", primary: "See Features", secondary: "View Pricing" },
    routes: [route("home", "Home", "home"), route("features", "Features", "features"), route("cases", "Cases", "cases"), route("pricing", "Pricing", "pricing"), route("contact", "Contact", "contact")],
    stats: [stat("Monthly plan", "월 39,000원"), stat("Setup time", "7 minutes"), stat("Goal hit", "84%")],
    chips: ["Dashboard first", "Soft grid", "Quiet motion"],
    design: { family: "Quiet finance OS", heroMode: "Dashboard-led first screen with KPI tiles and small charts.", background: "No photo hero. Use responsive mesh gradients and restrained depth.", motion: "Charts and target cards reveal with subtle layered motion.", keywords: ["dashboard SaaS", "quiet finance", "mesh background"] },
  },
  {
    id: "skin-clinic",
    brand: "ATELIER SKIN",
    industry: "Skin Clinic",
    category: "booking",
    summary: "Premium skin clinic with diagnosis-led booking, treatment programs, and medical trust cues.",
    backdrop: "minimal",
    themeKey: "monoClinic",
    imageStyle: "bold-minimal",
    homeMode: "Clinic stack",
    mobileRule: "Pin diagnosis CTA and open consult slots above every editorial section.",
    hero: { eyebrow: "Diagnosis First", title: "Lead with diagnosis and booking, not a generic beauty campaign.", subtitle: "The site should feel like a premium clinic with an active intake flow.", primary: "Start Diagnosis", secondary: "Book Visit" },
    routes: [route("home", "Home", "home"), route("programs", "Programs", "browse"), route("scan", "AI Scan", "detail"), route("booking", "Booking", "reserve"), route("clinic", "Clinic", "guide")],
    stats: [stat("Diagnosis fee", "29,000원"), stat("Consult type", "1:1"), stat("Return rate", "96%")],
    chips: ["Clinic calm", "Intake form", "Doctor trust"],
    design: { family: "Premium clinical booking", heroMode: "Treatment space photo with diagnosis CTA column and open-slot widget.", background: "Large clinic photography with soft shadowed cards floating upward.", motion: "Treatment cards and booking rows appear as layered translucent sheets.", keywords: ["clinic booking", "diagnosis-led", "soft layered panels"] },
  },
  {
    id: "arch-studio",
    brand: "PLAIN GRID",
    industry: "Architecture Studio",
    category: "portfolio",
    summary: "Editorial architecture portfolio that should feel like a real studio commission site.",
    backdrop: "grain",
    themeKey: "studioWarm",
    imageStyle: "bold-minimal",
    homeMode: "Editorial canvas",
    mobileRule: "Mobile should read like a visual brief deck with project cards and inquiry entry.",
    hero: { eyebrow: "Editorial Portfolio", title: "The homepage should behave like a studio issue, not a service funnel.", subtitle: "Lead with imagery, project voice, and commission confidence.", primary: "View Works", secondary: "Send Brief" },
    routes: [route("home", "Home", "home"), route("works", "Works", "works"), route("services", "Services", "services"), route("brief", "Brief", "brief"), route("contact", "Contact", "contact")],
    stats: [stat("Built projects", "32"), stat("Avg lead", "8 weeks"), stat("Focus", "Hospitality")],
    chips: ["Editorial spread", "Serif display", "Project voice"],
    design: { family: "Editorial studio portfolio", heroMode: "Image-led editorial spread with type anchored beside the photo.", background: "Large architecture photography with grain and paper warmth.", motion: "Blocks rise as layered editorial sheets and overlap on scroll.", keywords: ["editorial architecture", "serif portfolio", "image spread"] },
  },
  {
    id: "beauty-flash-sale",
    brand: "MELT POP",
    industry: "Beauty Flash Commerce",
    category: "commerce",
    summary: "High-tempo beauty commerce centered on kits, sale urgency, and palette-led shopping.",
    backdrop: "max",
    themeKey: "popRush",
    imageStyle: "maximal-pop",
    homeMode: "Sale poster board",
    mobileRule: "Show the hero price, kit choice, and checkout path before campaign storytelling.",
    hero: { eyebrow: "48H Flash Sale", title: "Treat the homepage like a glossy sale poster wall with live kit entry.", subtitle: "Everything should feel purchase-ready in the first seconds.", primary: "Shop Kits", secondary: "See Shades" },
    routes: [route("home", "Home", "home"), route("shop", "Shop", "browse"), route("shades", "Shades", "detail"), route("cart", "Cart", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Flash price", "29,900원"), stat("Shade count", "300"), stat("Ends in", "48h")],
    chips: ["Poster sale", "Price stickers", "Gloss texture"],
    design: { family: "Campaign-sale beauty", heroMode: "Poster-style first screen with giant price typography and layered kit cards.", background: "High-gloss campaign imagery with color stickers and overlapping sale tags.", motion: "Sale tags, swatches, and price strips float upward and cross each other.", keywords: ["beauty sale", "poster commerce", "gloss campaign"] },
  },
  {
    id: "festival-page",
    brand: "NOISE WAVE",
    industry: "Festival Event",
    category: "event",
    summary: "Festival site built around lineup discovery, timetable clarity, and ticket purchase.",
    backdrop: "retro",
    themeKey: "signalNight",
    imageStyle: "maximal-pop",
    homeMode: "Festival poster stack",
    mobileRule: "Open directly into lineup highlights, date, and ticket choice instead of long intro copy.",
    hero: { eyebrow: "Festival 2026", title: "The homepage should feel like a live event surface, not a brochure.", subtitle: "The first screen needs lineup signal, time, and ticket path immediately.", primary: "Buy Tickets", secondary: "See Lineup" },
    routes: [route("home", "Home", "home"), route("lineup", "Lineup", "lineup"), route("schedule", "Schedule", "schedule"), route("tickets", "Tickets", "tickets"), route("guide", "Guide", "guide")],
    stats: [stat("Day pass", "119,000원"), stat("Artists", "18"), stat("Gate opens", "14:00")],
    chips: ["Event poster", "Stage timing", "Ticket matrix"],
    design: { family: "Poster event system", heroMode: "Poster-led hero with lineup blocks, date stamp, and immediate ticket CTA.", background: "Large event imagery, spotlight gradients, and neon schedule cues.", motion: "Lineup cards and timing rails stack and rise like layered festival posters.", keywords: ["festival poster", "lineup discovery", "ticket matrix"] },
  },
  {
    id: "creator-club",
    brand: "RALLY HOUSE",
    industry: "Creator Community",
    category: "event",
    summary: "A creator community site with live feed energy, membership perks, and join flow.",
    backdrop: "max",
    themeKey: "popRush",
    imageStyle: "maximal-pop",
    homeMode: "Community live feed",
    mobileRule: "Lead with live updates, pass options, and join entry before community explanation.",
    hero: { eyebrow: "Creator Feed", title: "Open into a living club feed instead of a generic membership landing page.", subtitle: "Make the site feel active right now, with the join path always nearby.", primary: "Join Club", secondary: "View Perks" },
    routes: [route("home", "Home", "home"), route("feed", "Feed", "feed"), route("perks", "Perks", "perks"), route("join", "Join", "join"), route("guide", "Guide", "guide")],
    stats: [stat("Monthly pass", "12,000원"), stat("Live rooms", "48"), stat("Drop nights", "Every week")],
    chips: ["Live feed", "Pass cards", "Aura mesh"],
    design: { family: "Pop community platform", heroMode: "Feed-led first screen with live activity modules and join CTA beside it.", background: "No photo-first hero. Use mesh, aura, and soft physics-driven motion.", motion: "Feed cards and pass labels appear on different depth planes.", keywords: ["community feed", "membership join", "aurora mesh"] },
  },
  {
    id: "ev-mobility",
    brand: "ORBIT E",
    industry: "EV Mobility",
    category: "booking",
    summary: "An EV mobility site centered on model comparison, charge depth, and test-drive booking.",
    backdrop: "retro",
    themeKey: "signalNight",
    imageStyle: "retrofuture",
    homeMode: "Model compare dashboard",
    mobileRule: "Surface compare rows, charge logic, and test-drive CTA without burying them under brand copy.",
    hero: { eyebrow: "Drive Intelligence", title: "Lead with comparison and charge confidence before anything else.", subtitle: "The first screen should feel like a product compare console for real buyers.", primary: "Book Drive", secondary: "Compare Models" },
    routes: [route("home", "Home", "home"), route("models", "Models", "browse"), route("charge", "Charge", "detail"), route("drive", "Drive", "reserve"), route("support", "Support", "guide")],
    stats: [stat("Range", "540 km"), stat("Charge time", "18 min"), stat("Test wait", "12 days")],
    chips: ["Compare table", "Charge logic", "Metallic glow"],
    design: { family: "Future mobility compare", heroMode: "Comparison-led first screen with specs, range badges, and test-drive card visible at once.", background: "Hero vehicle imagery mixed with metallic reflections and responsive mesh depth.", motion: "Spec chips and compare rows glide in with measured technical precision.", keywords: ["EV compare", "test-drive booking", "technical dashboard"] },
  },
  {
    id: "gaming-gear",
    brand: "VOID ARC",
    industry: "Gaming Gear",
    category: "commerce",
    summary: "Gaming hardware commerce organized around setup bundles, specs, and aggressive cart entry.",
    backdrop: "retro",
    themeKey: "signalNight",
    imageStyle: "retrofuture",
    homeMode: "Setup command center",
    mobileRule: "Bring bundle spec, price, and cart action ahead of community or editorial blocks.",
    hero: { eyebrow: "Setup Bundle", title: "Make the homepage feel like a battle station selector, not a simple grid.", subtitle: "Specs and bundle entry should dominate the first screen.", primary: "View Bundles", secondary: "Open Cart" },
    routes: [route("home", "Home", "home"), route("gear", "Gear", "browse"), route("bundle", "Bundle", "detail"), route("cart", "Cart", "checkout"), route("support", "Support", "brand")],
    stats: [stat("Bundle price", "329,000원"), stat("Launch window", "24 hours"), stat("Mouse weight", "1.8g")],
    chips: ["Spec stack", "RGB depth", "Command UI"],
    design: { family: "Setup command commerce", heroMode: "A setup-control first screen with hardware visuals, spec modules, and bundle CTA.", background: "Dark desk setup imagery with RGB atmosphere and reactive line work.", motion: "Spec panels and cart chips animate like a command interface.", keywords: ["gaming setup", "bundle commerce", "spec UI"] },
  },
  {
    id: "ai-saas",
    brand: "SIGNAL GRID",
    industry: "AI Workflow SaaS",
    category: "saas",
    summary: "Workflow automation SaaS structured around flow boards, use cases, and pricing clarity.",
    backdrop: "retro",
    themeKey: "signalNight",
    imageStyle: "retrofuture",
    homeMode: "Workflow board",
    mobileRule: "Foreground workflow states, KPI cards, and a single product CTA instead of shrinking the desktop board.",
    hero: { eyebrow: "Workflow Board", title: "Open into an active AI workflow board instead of a startup headline stack.", subtitle: "Users should understand the product by glancing at the interface first.", primary: "Explore Flows", secondary: "See Pricing" },
    routes: [route("home", "Home", "home"), route("flows", "Flows", "features"), route("cases", "Cases", "cases"), route("pricing", "Pricing", "pricing"), route("contact", "Contact", "contact")],
    stats: [stat("Starter", "월 39,000원"), stat("Saved hours", "128h"), stat("Close rate", "31%")],
    chips: ["Workflow graph", "KPI tiles", "Mesh depth"],
    design: { family: "AI product board", heroMode: "Workflow-board homepage with logic nodes, KPI tiles, and action chips.", background: "Responsive mesh and aura depth rather than stock imagery.", motion: "Node clusters, metric chips, and CTA rails animate at different layers with restraint.", keywords: ["workflow SaaS", "graph board", "technical glow"] },
  },
  {
    id: "indie-bookstore",
    brand: "PAPER NOOK",
    industry: "Independent Bookstore",
    category: "commerce",
    summary: "A curated bookstore site that should feel like an editorial shelf, not a mass retailer.",
    backdrop: "collage",
    themeKey: "paperWarm",
    imageStyle: "collage-paper",
    homeMode: "Shelf editorial",
    mobileRule: "Treat picks, notes, and gift CTA like a magazine deck rather than a compressed grid.",
    hero: { eyebrow: "Curated Shelf", title: "Make the homepage read like a bookseller issue with a living shelf.", subtitle: "The site should feel hand-curated and giftable from the first viewport.", primary: "Browse Shelf", secondary: "Gift Picks" },
    routes: [route("home", "Home", "home"), route("shelf", "Shelf", "browse"), route("picks", "Picks", "detail"), route("gift", "Gift", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Shelf edits", "12"), stat("Gift set", "29,000원"), stat("Weekly notes", "3")],
    chips: ["Paper grain", "Editorial notes", "Shelf stacks"],
    design: { family: "Paper editorial commerce", heroMode: "Shelf-and-note first screen with editorial snippets and gift cues.", background: "Paper texture, torn edges, and warm photography rather than polished commerce blocks.", motion: "Book notes and shelf cards float like clipped paper pieces.", keywords: ["indie bookstore", "editorial shelf", "paper collage"] },
  },
  {
    id: "stationery-shop",
    brand: "CUT & NOTE",
    industry: "Stationery Shop",
    category: "commerce",
    summary: "A stationery commerce site built around kits, palette combinations, and tactile paper detail.",
    backdrop: "collage",
    themeKey: "paperWarm",
    imageStyle: "collage-paper",
    homeMode: "Paper kit board",
    mobileRule: "Prioritize kit composition, color combinations, and basket entry instead of long brand text.",
    hero: { eyebrow: "Paper Kit", title: "The first screen should feel like a desk board of kit pieces and color combinations.", subtitle: "Users should understand the product through arrangement, not explanation.", primary: "Browse Kits", secondary: "Open Basket" },
    routes: [route("home", "Home", "home"), route("kits", "Kits", "browse"), route("colors", "Colors", "detail"), route("basket", "Basket", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Kit price", "34,900원"), stat("Palette sets", "18"), stat("Wrap option", "Available")],
    chips: ["Tactile desk", "Palette board", "Paper overlap"],
    design: { family: "Tactile collage commerce", heroMode: "A board of stationery pieces, taped notes, and visible kit assembly.", background: "Paper material, taped edges, and physical texture with soft motion.", motion: "Items behave like light paper pieces sliding and overlapping.", keywords: ["stationery collage", "tactile commerce", "desk board"] },
  },
  {
    id: "local-cafe",
    brand: "TABLE WARM",
    industry: "Cafe Reservation",
    category: "booking",
    summary: "A cafe site focused on today's menu, seat availability, and direct reservation entry.",
    backdrop: "hand",
    themeKey: "cafeWarm",
    imageStyle: "collage-paper",
    homeMode: "Cafe window",
    mobileRule: "Put today's menu and seat reservation in the first two blocks with no extra ceremony.",
    hero: { eyebrow: "Today at Cafe", title: "Open like a real storefront window with menu and seating already visible.", subtitle: "The site should feel walk-in friendly and alive, not like a lifestyle magazine.", primary: "Reserve Seat", secondary: "See Menu" },
    routes: [route("home", "Home", "home"), route("menu", "Menu", "browse"), route("visit", "Visit", "detail"), route("reserve", "Reserve", "reserve"), route("info", "Info", "guide")],
    stats: [stat("Open seats", "7"), stat("Table hold", "12 min"), stat("Set menu", "18,000원")],
    chips: ["Storefront photo", "Menu board", "Warm notes"],
    design: { family: "Warm storefront booking", heroMode: "Storefront hero with today's menu board and reservation module visible immediately.", background: "Big cafe imagery, paper menu notes, and gentle hand-crafted depth.", motion: "Menu plates and reservation notes lift softly over the storefront image.", keywords: ["cafe reservation", "storefront layout", "menu board"] },
  },
  {
    id: "boutique-hotel",
    brand: "HOTEL STILL",
    industry: "Boutique Hotel",
    category: "booking",
    summary: "A boutique hotel site driven by room imagery, stay finder, and package selection.",
    backdrop: "grain",
    themeKey: "grainStone",
    imageStyle: "grain-editorial",
    homeMode: "Stay finder hero",
    mobileRule: "Show the room photo first but keep the stay finder and offer CTA immediately attached to it.",
    hero: { eyebrow: "Stay Finder", title: "The site should feel like a real hotel homepage with booking intent from frame one.", subtitle: "Room imagery and reservation control need to coexist in the opening view.", primary: "Book Stay", secondary: "See Rooms" },
    routes: [route("home", "Home", "home"), route("rooms", "Rooms", "browse"), route("offers", "Offers", "detail"), route("booking", "Booking", "reserve"), route("guide", "Guide", "guide")],
    stats: [stat("Night rate", "189,000원"), stat("Check-in", "15:00"), stat("Packages", "4")],
    chips: ["Full-bleed photo", "Stay finder", "Package cards"],
    design: { family: "Boutique stay booking", heroMode: "Large room photography with the stay finder layered directly on top.", background: "High-resolution room imagery and floating blocks that rise over the photo on scroll.", motion: "Package cards and room details reveal as overlapping sheets.", keywords: ["hotel booking", "room image first", "floating stay finder"] },
  },
  {
    id: "perfume-house",
    brand: "MOSS & AMBER",
    industry: "Perfume House",
    category: "commerce",
    summary: "A perfume site built around mood imagery, note structure, and curated set purchase.",
    backdrop: "grain",
    themeKey: "grainStone",
    imageStyle: "grain-editorial",
    homeMode: "Scent mood film",
    mobileRule: "Turn notes, set price, and gift CTA into touch-ready cards instead of shrinking a mood canvas.",
    hero: { eyebrow: "Scent Mood", title: "Treat the homepage like a perfume editorial with note cards and set entry.", subtitle: "The first screen should feel atmospheric but still commercially legible.", primary: "Browse Sets", secondary: "Gift Select" },
    routes: [route("home", "Home", "home"), route("sets", "Sets", "browse"), route("notes", "Notes", "detail"), route("gift", "Gift", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Set price", "74,000원"), stat("Core notes", "21"), stat("Gift wrap", "Included")],
    chips: ["Mood film", "Note cards", "Gift path"],
    design: { family: "Mood-led perfume house", heroMode: "Editorial mood canvas with layered note cards and direct set entry.", background: "Cinematic fragrance visuals with soft blur, depth, and quiet layered reveals.", motion: "Note cards and scent descriptors drift in layered motion over the hero visual.", keywords: ["perfume editorial", "note cards", "mood commerce"] },
  },
  {
    id: "furniture-store",
    brand: "MOSS HOME",
    industry: "Furniture Commerce",
    category: "commerce",
    summary: "A furniture site centered on room planning, bundle shopping, and spatial exploration.",
    backdrop: "organic",
    themeKey: "organicSoft",
    imageStyle: "organic-soft",
    homeMode: "Room planner",
    mobileRule: "Surface room choices and planner CTA as the main behavior, not as secondary footer content.",
    hero: { eyebrow: "Room Planner", title: "Open with a room-planning surface instead of a standard product hero.", subtitle: "The first screen should let users choose a room mood immediately.", primary: "Plan Room", secondary: "View Bundle" },
    routes: [route("home", "Home", "home"), route("rooms", "Rooms", "browse"), route("planner", "Planner", "detail"), route("cart", "Cart", "checkout"), route("service", "Service", "brand")],
    stats: [stat("Bundle options", "12"), stat("Lead time", "3 weeks"), stat("Room sets", "9")],
    chips: ["Room mood", "Planner CTA", "Organic depth"],
    design: { family: "Spatial planning commerce", heroMode: "Room planner-led homepage with room selectors and bundle CTA visible immediately.", background: "Large interior imagery, soft organic gradients, and layered planner panels.", motion: "Room tags and planner cards float in like layout sheets.", keywords: ["furniture planner", "room-based commerce", "organic depth"] },
  },
  {
    id: "youth-fashion",
    brand: "BOP BOP",
    industry: "Youth Fashion",
    category: "commerce",
    summary: "A youth fashion site built as a lookbook rail with strong image sequencing and fast shop entry.",
    backdrop: "playful",
    themeKey: "playBright",
    imageStyle: "playful-type",
    homeMode: "Lookbook rail",
    mobileRule: "Transform the lookbook into swipeable outfit stacks with a direct shop CTA on each block.",
    hero: { eyebrow: "Lookbook Rail", title: "Open into a lookbook strip, not a generic apparel storefront.", subtitle: "Outfit imagery and shop entry should feel linked from the first frame.", primary: "Shop Looks", secondary: "Open Cart" },
    routes: [route("home", "Home", "home"), route("looks", "Looks", "browse"), route("shop", "Shop", "detail"), route("cart", "Cart", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Size range", "XS-XL"), stat("Drop sale", "15%"), stat("Entry price", "59,000원+")],
    chips: ["Lookbook rail", "Type-forward", "Youth motion"],
    design: { family: "Lookbook commerce", heroMode: "Lookbook-led hero where images and shop CTAs live in the same visual rail.", background: "Campaign imagery, bright typography, and playful layers rather than minimalist white space.", motion: "Looks and tags glide like a fast-moving editorial rail.", keywords: ["lookbook fashion", "type-led commerce", "image rail"] },
  },
  {
    id: "jewelry-brand",
    brand: "LUNE FORM",
    industry: "Jewelry Brand",
    category: "commerce",
    summary: "A jewelry site structured around collection reveals, bespoke inquiry, and gallery-level image treatment.",
    backdrop: "chrome",
    themeKey: "chromePearl",
    imageStyle: "chrome-luxe",
    homeMode: "Collection gallery",
    mobileRule: "Convert the collection view into clean stacked cards with direct bespoke and consult entry.",
    hero: { eyebrow: "Collection House", title: "Present the homepage like a collection gallery with conversion built into the experience.", subtitle: "Collection reveal and bespoke inquiry should feel equally intentional.", primary: "View Collection", secondary: "Book Consult" },
    routes: [route("home", "Home", "home"), route("collection", "Collection", "browse"), route("bespoke", "Bespoke", "detail"), route("consult", "Consult", "checkout"), route("brand", "Brand", "brand")],
    stats: [stat("Entry piece", "129,000원"), stat("Consult type", "Private"), stat("Lead time", "2 weeks")],
    chips: ["Gallery reveal", "Macro product", "Metal sheen"],
    design: { family: "Collection gallery commerce", heroMode: "Gallery-led hero with macro product imagery and a clean consult CTA block.", background: "High-resolution jewelry imagery, chrome reflections, and soft physical depth.", motion: "Collection panels and consult cards rise with subtle metallic sheen.", keywords: ["jewelry gallery", "macro product", "bespoke consult"] },
  },
];

export const siteCatalog = rawSites.map((site) => {
  const localized = localizedSites[site.id] ?? {};

  return {
    ...site,
    ...localized,
    stats: site.stats.map((item) => ({ ...item, label: statLabels[item.label] ?? item.label })),
    theme: themes[site.themeKey],
    motion: motionPresets[site.id] ?? { profile: "cinematic-depth", layout: "poster", homeVariant: "cinematic-home", tempo: "medium" },
    legacyImages: {
      brand: buildImage(site.imageStyle, site.id, "brand"),
      product: buildImage(site.imageStyle, site.id, "product"),
      scene: buildImage(site.imageStyle, site.id, "scene"),
    },
    images: {
      brand: buildImageV2(site.id, "brand"),
      product: buildImageV2(site.id, "product"),
      scene: buildImageV2(site.id, "scene"),
    },
  };
});

export const siteCatalogById = Object.fromEntries(siteCatalog.map((site) => [site.id, site]));

export function getSiteCatalogEntry(siteId) {
  return siteCatalogById[siteId] ?? null;
}

export function getRoutesForSite(siteId) {
  return getSiteCatalogEntry(siteId)?.routes ?? [route("home", "Home", "home")];
}

export function getBlueprintForSite(siteId) {
  return getSiteCatalogEntry(siteId)?.design ?? {
    family: "독립형 디지털 브랜드",
    heroMode: "첫 화면만 봐도 서비스가 이해되는 구조여야 하며 흔한 히어로 스택을 쓰지 않는다.",
    background: "고해상도 이미지 월드 혹은 절제된 반응형 메시 배경 중 하나를 사용한다.",
    motion: "깊이감 있는 레이어 연출을 쓰되 콘텐츠 가독성을 해치지 않는다.",
    keywords: ["독립 사이트", "비템플릿 레이아웃"],
  };
}

export function getRouteDescription(kind) {
  return routeKindDescriptions[kind] ?? "직접 행동이 바로 이어지는 실제 운영형 페이지처럼 설계한다.";
}

export function getStageHeight(kind, device) {
  return stageHeights[kind]?.[device] ?? (device === "mobile" ? 940 : 1320);
}
