export const styleSamples = [
  {
    id: "neo-brutal",
    preview: "neo",
    name: "네오 브루탈리즘",
    en: "Neo Brutal",
    badge: "Bold / Raw",
    category: "실험형 전환 페이지",
    summary: "강한 대비와 두꺼운 경계로 시선을 먼저 붙잡는 스타일",
    asset: "conversion-board.png",
    theme: { shell: "#f8ef64", surface: "#fffdf3", panel: "#ffffff", text: "#111111", muted: "#4a443c", accent: "#ff6b6b", accentSoft: "#7dd3fc", border: "#111111", buttonText: "#111111", shadow: "10px 10px 0 #111111" },
    industries: [
      {
        id: "sneaker-drop",
        label: "스니커즈 드롭 스토어",
        company: "RIFT/01",
        mode: "commerce",
        nav: ["New Drop", "Size", "Lookbook", "Cart"],
        title: "드롭 일정부터 사이즈 추천까지 한 번에 끝내는 스트릿 스니커즈 스토어",
        desc: "한정 드롭, 빠른 재고 확인, 코디 추천, 장바구니 전환을 거칠고 직설적인 톤으로 보여주는 페이지입니다.",
        story: "RIFT/01은 신제품 공개 순간의 긴장감과 결제 직전의 판단을 동시에 잡는 스니커즈 스토어입니다. 복잡한 설명 대신 지금 사야 하는 이유와 사이즈 선택 근거를 먼저 보여줍니다.",
        stats: [["93%", "사이즈 매칭 정확도"], ["12m", "평균 완판 시간"], ["4.8/5", "만족도"]],
        values: [["Fast Scan", "재고와 가격을 바로 읽히게 배치합니다."], ["Fit First", "발 길이와 선호 핏으로 사이즈를 추천합니다."], ["Style Match", "가지고 있는 옷과 맞는 룩을 같이 제안합니다."]],
        offers: [["Aero Runner", "이번 주 메인 드롭 / 240-285", "KRW 229,000"], ["Frame High", "블랙 리미티드 에디션", "KRW 269,000"], ["Cargo Shell Set", "추천 코디 번들", "KRW 189,000"]],
        tools: [["사이즈 추천", "발 길이와 선호 착화감을 바탕으로 사이즈를 추천합니다."], ["보유 옷 매칭", "가지고 있는 팬츠와 어울리는 신발을 조합합니다."], ["드롭 알림 안내", "관심 모델 재입고와 발매 시간을 바로 안내합니다."]],
        quote: "브랜드 설명보다 먼저 구매 판단을 도와주는 구조가 필요했습니다.",
        author: "Drop Director / RIFT/01",
        panel: { badge: "Cart Preview", title: "장바구니 전 마지막 판단", text: "추천 사이즈와 어울리는 룩, 배송 옵션을 같은 화면에서 확인합니다.", rows: [["추천 사이즈", "270 / 적합도 93%"], ["함께 보면 좋은 룩", "와이드 카고 팬츠"], ["도착 예정", "내일 출고"]], primary: "장바구니 담기", secondary: "사이즈 보기" },
      },
      {
        id: "supplement-brand",
        label: "퍼포먼스 보충제 브랜드",
        company: "PUNCH FUEL",
        mode: "commerce",
        nav: ["Products", "Routine", "Compare", "Subscribe"],
        title: "루틴 설계부터 정기구독까지 한 번에 이어지는 피트니스 보충제 브랜드",
        desc: "성분 비교, 목표별 추천, 섭취 시간 제안, 정기구독 전환을 강하고 단순한 화면으로 보여줍니다.",
        story: "PUNCH FUEL은 제품을 파는 대신 루틴을 먼저 설계해주는 보충제 브랜드입니다. 고객은 무슨 제품을 사야 하는지보다 어떤 조합으로 먹어야 하는지 먼저 알고 싶다는 전제에서 출발합니다.",
        stats: [["2.1x", "구독 전환"], ["18k", "루틴 생성 수"], ["4.9/5", "재구매 만족도"]],
        values: [["Routine First", "제품보다 목표와 섭취 습관을 먼저 묻습니다."], ["Ingredient Clear", "성분과 용량을 빠르게 비교할 수 있습니다."], ["No Guesswork", "운동 시간과 목적에 맞는 조합을 제시합니다."]],
        offers: [["Strength Stack", "웨이 + 크레아틴 조합", "KRW 119,000"], ["Cut Stack", "단백질 + L카르니틴 조합", "KRW 98,000"], ["Starter Box", "14일 체험 패키지", "KRW 49,000"]],
        tools: [["루틴 추천", "운동 시간과 목표를 입력하면 섭취 플랜을 짜줍니다."], ["성분 비교 요약", "비슷한 제품 간 차이를 한 화면에서 보여줍니다."], ["리필 안내", "복용 주기에 맞춰 재구매 시점을 알려줍니다."]],
        quote: "고객은 제품명이 아니라 루틴을 사고 싶어 했습니다.",
        author: "Brand Lead / PUNCH FUEL",
        panel: { badge: "Routine Builder", title: "내 루틴으로 시작", text: "목표와 운동 시간을 고르면 맞는 조합과 섭취 타이밍을 추천합니다.", rows: [["목표", "근력 증가"], ["운동 시간", "오후 7시"], ["추천 플랜", "Strength Stack"]], primary: "루틴 추천 받기", secondary: "정기구독 보기" },
      },
      {
        id: "boxing-gym",
        label: "복싱짐 멤버십",
        company: "UPPERCUT CLUB",
        mode: "booking",
        nav: ["Classes", "Trainers", "Match", "Join"],
        title: "분위기와 코치 매칭까지 한 번에 보여주는 복싱짐 소개 페이지",
        desc: "클래스 강도, 트레이너 성향, 체험 예약, 매칭까지 강한 에너지로 이어지는 멤버십 페이지입니다.",
        story: "UPPERCUT CLUB은 수업 설명보다 먼저 체육관 분위기와 운동 강도를 전달합니다. 입문자도 겁먹지 않도록 체험 예약과 코치 매칭을 단순한 흐름으로 설계합니다.",
        stats: [["120+", "주간 클래스"], ["87%", "체험 후 등록률"], ["4.9/5", "코치 만족도"]],
        values: [["Energy Front", "화면 첫인상에서 수업 분위기를 전달합니다."], ["Coach Match", "목표와 성향에 맞는 코치를 붙입니다."], ["Easy Booking", "체험 신청까지 클릭 수를 줄입니다."]],
        offers: [["Starter Class", "입문자 4주 프로그램", "KRW 169,000"], ["Fight Conditioning", "주 3회 집중반", "KRW 249,000"], ["Private Punch", "1:1 8회 코칭", "KRW 520,000"]],
        tools: [["클래스 추천", "체력과 목표를 입력하면 반을 추천합니다."], ["자세 피드백", "기본 동작 영상을 분석해 교정 포인트를 줍니다."], ["트레이너 매칭", "학습 스타일에 맞는 코치를 연결합니다."]],
        quote: "체육관의 온도와 등록 흐름이 같은 화면에서 느껴져야 했습니다.",
        author: "Studio Manager / UPPERCUT CLUB",
        panel: { badge: "Booking Panel", title: "오늘 체험 예약", text: "가능한 시간과 목표를 고르면 추천 클래스와 코치를 바로 보여줍니다.", rows: [["희망 시간", "오늘 19:30"], ["추천 반", "Starter Class"], ["추천 코치", "Coach Min"]], primary: "체험 예약하기", secondary: "추천 클래스 보기" },
      },
    ],
  },
  {
    id: "bold-minimal",
    preview: "minimal",
    name: "볼드 미니멀",
    en: "Bold Minimal",
    badge: "Calm / Focus",
    category: "클린 전환 페이지",
    summary: "불필요한 장식을 빼고 구조와 카피로 설득하는 스타일",
    asset: "hero-studio.png",
    theme: { shell: "#f4f1eb", surface: "#ffffff", panel: "#fcfbf8", text: "#101418", muted: "#5e6872", accent: "#111111", accentSoft: "#e7ebf0", border: "#d9dde2", buttonText: "#ffffff", shadow: "0 24px 52px rgba(15,23,42,0.08)" },
    industries: [
      {
        id: "wealth-app",
        label: "자산관리 앱",
        company: "CLARO",
        mode: "saas",
        nav: ["Overview", "Goals", "Coach", "Start"],
        title: "예산과 소비 흐름을 한 번에 정리해주는 미니멀 자산관리 앱",
        desc: "목표 기반 플랜, 소비 요약, 카드 비교, 코칭을 조용하지만 단단한 구조로 보여주는 금융 서비스 페이지입니다.",
        story: "CLARO는 숫자를 보여주는 앱이 아니라 돈의 흐름을 정리해주는 코치 역할을 맡습니다. 광고성 문구를 줄이고 필요한 판단 정보만 남기는 것이 핵심입니다.",
        stats: [["1.8x", "목표 달성률"], ["8m", "주간 사용 시간"], ["4.9/5", "리포트 만족도"]],
        values: [["Clarity", "현재 소비와 목표 사이 간격을 쉽게 읽힙니다."], ["Control", "카드와 계좌를 하나의 플랜으로 묶습니다."], ["Quiet Trust", "과장 없는 카피와 데이터 중심 구조를 유지합니다."]],
        offers: [["Goal Planner", "목표 금액과 기간 설계", "Included"], ["Card Compare", "혜택 자동 비교", "Included"], ["Weekly Summary", "주간 리포트 발송", "Included"]],
        tools: [["소비 코치", "새는 비용과 반복 지출을 찾아줍니다."], ["목표별 플랜 추천", "여행, 비상금, 대출 상환 플랜을 제안합니다."], ["카드 매칭", "지출 패턴에 맞는 카드를 추천합니다."]],
        quote: "금융 서비스일수록 조용한 신뢰감이 더 중요했습니다.",
        author: "Product Owner / CLARO",
        panel: { badge: "Coach", title: "이번 달 진단", text: "가장 큰 지출 변화와 줄일 수 있는 항목을 짧게 요약해줍니다.", rows: [["추가 소비", "KRW 420,000"], ["핵심 항목", "배달 / 구독"], ["추천 카드", "Claro Everyday"]], primary: "코치 시작", secondary: "데모 보기" },
      },
      {
        id: "skin-clinic",
        label: "프리미엄 스킨 클리닉",
        company: "ATELIER SKIN",
        mode: "booking",
        nav: ["Programs", "Doctors", "Scan", "Book"],
        title: "진단과 루틴 설계를 먼저 보여주는 프리미엄 스킨 클리닉",
        desc: "의료진 소개, 프로그램 구조, 피부 스캔, 상담 예약 흐름을 단정하게 정리한 예약형 페이지입니다.",
        story: "ATELIER SKIN은 시술 광고보다 진단과 유지 관리의 신뢰를 먼저 보여주는 클리닉입니다. 톤은 조용하지만 예약 전환까지의 흐름은 빠르게 이어집니다.",
        stats: [["24h", "상담 응답 시간"], ["91%", "재방문율"], ["4.9/5", "상담 만족도"]],
        values: [["Diagnosis First", "상태 파악과 기록이 먼저입니다."], ["Trustworthy Tone", "과장 없는 안내와 명료한 설명을 유지합니다."], ["Routine Care", "시술 이후 관리 플로우까지 이어집니다."]],
        offers: [["Barrier Restore", "민감 피부 회복 프로그램", "Consultation"], ["Tone Reset", "색소·톤 집중 관리", "Consultation"], ["Clinic Membership", "월간 루틴 관리", "KRW 390,000"]],
        tools: [["피부 스캔", "붉음기와 모공, 수분 상태를 간단히 요약합니다."], ["루틴 추천", "진단 결과에 맞는 홈케어 루틴을 제안합니다."], ["상담 안내", "준비사항과 회복 안내를 미리 제공합니다."]],
        quote: "예약 전부터 전문성과 안정감을 느끼게 하는 구조가 필요했습니다.",
        author: "Director / ATELIER SKIN",
        panel: { badge: "Consultation", title: "첫 상담 예약", text: "고민 부위와 가능한 시간을 입력하면 맞는 프로그램과 상담 일정을 제안합니다.", rows: [["주요 고민", "민감도 / 붉은기"], ["추천 프로그램", "Barrier Restore"], ["가능 일정", "목요일 14:00"]], primary: "상담 예약하기", secondary: "스캔 시작" },
      },
      {
        id: "arch-studio",
        label: "건축·공간 설계 스튜디오",
        company: "PLAIN GRID",
        mode: "consulting",
        nav: ["Works", "Process", "Brief", "Contact"],
        title: "작업 철학과 상담 흐름을 같은 밀도로 보여주는 건축 스튜디오 페이지",
        desc: "작업 사례, 프로젝트 흐름, 브리프 입력, 상담 문의를 절제된 편집형 레이아웃으로 묶었습니다.",
        story: "PLAIN GRID는 포트폴리오만 나열하지 않고 어떤 기준으로 공간을 해석하는지부터 설명합니다. 의뢰 전 고객이 프로젝트 흐름을 상상할 수 있게 만드는 것이 목표입니다.",
        stats: [["68", "완료 프로젝트"], ["5주", "콘셉트 설계 기간"], ["92%", "상담 전환율"]],
        values: [["Context", "공간의 목적과 브랜드 맥락을 함께 읽습니다."], ["System", "설계, 시공, 운영 흐름을 연결합니다."], ["Edit", "불필요한 요소를 덜어내 구조를 남깁니다."]],
        offers: [["Retail Space", "상업 공간 설계", "Proposal"], ["Residential Renewal", "주거 리노베이션", "Proposal"], ["Concept Package", "브랜드 공간 콘셉트", "KRW 2.4M+"]],
        tools: [["브리프 분석", "공간 용도와 예산을 요약해줍니다."], ["무드보드 추천", "참고 이미지 기반 방향을 제안합니다."], ["상담 안내", "프로젝트 범위와 준비사항을 정리합니다."]],
        quote: "작업 이미지보다 프로젝트를 풀어가는 태도가 먼저 보여야 했습니다.",
        author: "Principal / PLAIN GRID",
        panel: { badge: "Project Brief", title: "프로젝트 문의", text: "공간 종류와 규모, 원하는 무드를 입력하면 상담 범위와 진행 방식을 안내합니다.", rows: [["공간 유형", "카페 / 42평"], ["무드", "Quiet Minimal"], ["예산 범위", "KRW 80M - 120M"]], primary: "프로젝트 문의", secondary: "작업 방식 보기" },
      },
    ],
  },
  {
    id: "maximal-pop",
    preview: "max",
    name: "맥시멀 팝",
    en: "Maximal Pop",
    badge: "Busy / Loud",
    category: "감정 자극형 페이지",
    summary: "색과 정보, 리듬을 겹쳐 강한 반응을 끌어내는 스타일",
    asset: "style-compare.png",
    theme: { shell: "#ff5f5f", surface: "#211a33", panel: "rgba(255,255,255,0.12)", text: "#ffffff", muted: "rgba(255,255,255,0.72)", accent: "#ffd84d", accentSoft: "#ff92d4", border: "rgba(255,255,255,0.16)", buttonText: "#111111", shadow: "0 28px 60px rgba(17,17,31,0.32)" },
    industries: [
      {
        id: "beauty-flash-sale",
        label: "뷰티 플래시 세일",
        company: "MELT POP",
        mode: "commerce",
        nav: ["Drop", "Kits", "Shade", "Cart"],
        title: "한정 특가와 컬러 실험을 한 화면에서 밀어붙이는 뷰티 드롭 페이지",
        desc: "세일 카운트다운, 세트 구성, 컬러 비교, 가상 발색을 넘치는 에너지로 보여주는 뷰티 커머스입니다.",
        story: "MELT POP은 할인 정보만 전달하지 않습니다. 컬러를 고르는 재미와 조합을 고르는 속도를 동시에 살리는 것이 핵심입니다.",
        stats: [["4.2x", "런칭일 전환"], ["19k", "가상 발색 사용"], ["62%", "세트 구매 비중"]],
        values: [["Sale Energy", "특가와 혜택을 강하게 밀어줍니다."], ["Color Play", "컬러 비교를 재미있는 화면으로 바꿉니다."], ["Bundle First", "단품보다 세트 구성을 먼저 제안합니다."]],
        offers: [["Candy Blur Set", "틴트 3종 세트", "KRW 39,000"], ["Glow Shot", "하이라이터 한정 컬러", "KRW 22,000"], ["Night Heat Kit", "메이크업 풀 세트", "KRW 76,000"]],
        tools: [["발색 미리보기", "피부 톤에 맞춰 립·치크 발색을 보여줍니다."], ["보유 화장품 매칭", "가지고 있는 제품과 어울리는 조합을 추천합니다."], ["세일 안내", "마감 시간과 쿠폰 조건을 빠르게 안내합니다."]],
        quote: "특가 페이지도 브랜드 경험이 되도록 만들고 싶었습니다.",
        author: "Campaign Lead / MELT POP",
        panel: { badge: "Checkout Boost", title: "마감 전 추천 조합", text: "지금 담은 제품 기준으로 할인율이 가장 좋은 세트 구성을 다시 제안합니다.", rows: [["남은 시간", "03:12:44"], ["추가 할인", "세트 구매 시 12%"], ["추천 조합", "Candy Blur + Glow Shot"]], primary: "세트로 구매하기", secondary: "가상 발색 보기" },
      },
      {
        id: "festival-page",
        label: "뮤직 페스티벌 티켓 페이지",
        company: "NOISE WAVE",
        mode: "ticketing",
        nav: ["Line-up", "Schedule", "Planner", "Tickets"],
        title: "라인업과 체험 동선을 폭발적으로 보여주는 뮤직 페스티벌 페이지",
        desc: "아티스트 라인업, 시간표, 현장 맵, 티켓 등급과 플래너를 화려한 구도 안에 몰아 넣은 페이지입니다.",
        story: "NOISE WAVE는 티켓을 파는 페이지이면서 동시에 현장 경험의 예고편입니다. 고객이 어떤 하루를 보내게 될지 장면 단위로 상상하게 합니다.",
        stats: [["74%", "얼리버드 소진"], ["11k", "플래너 저장 수"], ["3.6m", "평균 체류 시간"]],
        values: [["High Tension", "시선을 빠르게 이동시키며 기대감을 높입니다."], ["Plan Fast", "복잡한 타임테이블을 직관적으로 나눕니다."], ["Ticket Push", "티켓 등급별 혜택을 강하게 밀어줍니다."]],
        offers: [["Early Bird", "2일권 / 한정 수량", "KRW 129,000"], ["Wave Pass", "VIP 존 포함", "KRW 249,000"], ["Crew Pack", "3인 묶음 티켓", "KRW 339,000"]],
        tools: [["타임테이블 플래너", "좋아하는 장르 기준으로 동선을 짜줍니다."], ["현장 혼잡 예측", "시간대별 추천 이동 루트를 안내합니다."], ["티켓 안내", "좌석, 입장, 반입 가능 물품을 답변합니다."]],
        quote: "페스티벌은 정보보다 리듬으로 먼저 설득해야 했습니다.",
        author: "Experience Director / NOISE WAVE",
        panel: { badge: "Ticket Desk", title: "내 일정에 맞는 티켓 찾기", text: "방문 날짜와 관심 아티스트를 입력하면 가장 적합한 티켓과 이동 플랜을 제안합니다.", rows: [["방문 일정", "토요일"], ["추천 티켓", "Wave Pass"], ["핵심 스테이지", "Main / Neon"]], primary: "티켓 구매", secondary: "플래너 시작" },
      },
      {
        id: "creator-club",
        label: "크리에이터 멤버십 클럽",
        company: "RALLY HOUSE",
        mode: "membership",
        nav: ["Benefits", "Community", "Brief", "Join"],
        title: "멤버십 혜택과 크리에이터 협업 흐름을 강하게 드러내는 커뮤니티 페이지",
        desc: "참여 혜택, 크루 소개, 이벤트 일정, 브리프 안내을 빠르고 시끄러운 톤으로 정리한 멤버십 페이지입니다.",
        story: "RALLY HOUSE는 단순 커뮤니티가 아니라 같이 만들고 같이 팔아보는 실험실에 가깝습니다. 그래서 혜택과 분위기를 동시에 크게 보여줍니다.",
        stats: [["6.3k", "활성 멤버"], ["41%", "이벤트 재참여"], ["2.8x", "협업 신청 증가"]],
        values: [["Club Identity", "멤버십에 들어가고 싶어지는 분위기를 만듭니다."], ["Collab Ready", "이벤트와 협업 기회를 바로 연결합니다."], ["Fast Join", "가입 전 망설임을 줄이는 혜택 구조를 보여줍니다."]],
        offers: [["Starter Crew", "월간 세션 참여", "KRW 39,000/mo"], ["Builder Crew", "포트폴리오 피드백 포함", "KRW 79,000/mo"], ["Launch Crew", "브랜드 협업 매칭", "KRW 159,000/mo"]],
        tools: [["브리프 안내", "콘텐츠 아이디어와 협업 제안을 정리합니다."], ["포트폴리오 리뷰", "작업물 강점과 보완점을 요약합니다."], ["이벤트 추천", "관심 분야 기반 밋업과 클래스 추천을 제공합니다."]],
        quote: "가입 혜택만이 아니라 같이 움직이는 장면이 보여야 했습니다.",
        author: "Community Lead / RALLY HOUSE",
        panel: { badge: "Join Flow", title: "어떤 크루가 맞는지 진단", text: "활동 목적과 작업 분야를 넣으면 추천 플랜과 바로 참여 가능한 이벤트를 보여줍니다.", rows: [["활동 목적", "브랜드 협업"], ["추천 플랜", "Launch Crew"], ["이번 주 이벤트", "Creator Match Night"]], primary: "멤버십 시작", secondary: "브리프 받기" },
      },
    ],
  },
  {
    id: "retrofuture",
    preview: "retro",
    name: "레트로퓨처",
    en: "Retrofuture",
    badge: "Neon / Sci-fi",
    category: "미래 감성형 페이지",
    summary: "네온과 SF 무드로 제품의 세계관을 먼저 각인시키는 스타일",
    asset: "style-compare.png",
    theme: { shell: "#09071d", surface: "#0f1228", panel: "rgba(21,34,58,0.82)", text: "#ebfaff", muted: "rgba(203,241,255,0.72)", accent: "#39d5ff", accentSoft: "#ff6fe4", border: "rgba(57,213,255,0.22)", buttonText: "#071018", shadow: "0 20px 52px rgba(1,8,18,0.42)" },
    industries: [
      {
        id: "ev-mobility",
        label: "전기 모빌리티 브랜드",
        company: "ORBIT E",
        mode: "commerce",
        nav: ["Models", "Range", "Route", "Reserve"],
        title: "주행 거리와 예약 상담을 미래적인 무드로 압축한 전기 모빌리티 페이지",
        desc: "모델 비교, 주행 거리, 충전 정보, 경로 추천, 시승 예약을 세계관형 레이아웃으로 보여주는 페이지입니다.",
        story: "ORBIT E는 차량 스펙을 나열하는 대신 전동화 라이프스타일을 먼저 경험하게 합니다. 기술적 신뢰와 감각적 톤을 동시에 유지합니다.",
        stats: [["612km", "최대 주행 거리"], ["38m", "급속 충전 80%"], ["2.3x", "시승 예약 증가"]],
        values: [["Signal Clear", "핵심 성능 수치를 강하게 띄웁니다."], ["Route Ready", "실사용 기준 정보를 보여줍니다."], ["Future Tone", "기술 브랜드에 맞는 세계관을 만듭니다."]],
        offers: [["Orbit S", "도심형 전기 SUV", "From KRW 58.9M"], ["Orbit GT", "장거리 퍼포먼스 라인", "From KRW 71.2M"], ["Home Charger Kit", "설치 패키지 포함", "Consultation"]],
        tools: [["주행 루트 추천", "평소 이동 거리 기준 충전 루틴을 계산합니다."], ["집 충전 적합도 확인", "주거 형태에 맞는 설치 옵션을 안내합니다."], ["시승 안내", "모델별 차이와 예약 가능 지점을 답변합니다."]],
        quote: "기술 설명과 브랜드 환상을 같은 톤으로 보여주고 싶었습니다.",
        author: "Brand Strategist / ORBIT E",
        panel: { badge: "Drive Panel", title: "내 주행 패턴에 맞는 모델 찾기", text: "출퇴근 거리와 탑승 인원을 넣으면 적합한 모델과 충전 플랜을 추천합니다.", rows: [["일 평균 주행", "58km"], ["추천 모델", "Orbit S"], ["다음 시승 가능", "토요일 11:00"]], primary: "시승 예약", secondary: "루트 보기" },
      },
      {
        id: "gaming-gear",
        label: "게이밍 기어 스토어",
        company: "VOID ARC",
        mode: "commerce",
        nav: ["Gear", "Setups", "Match", "Cart"],
        title: "장비 성능과 셋업 조합을 한 번에 보여주는 게이밍 기어 스토어",
        desc: "키보드, 마우스, 모니터, 셋업 번들, 장비 매칭을 네온 UI 스타일로 풀어낸 커머스 페이지입니다.",
        story: "VOID ARC는 제품 개별 스펙보다 플레이 스타일에 맞는 셋업을 먼저 보여줍니다. 그래서 장바구니보다 장비 조합 추천이 먼저 등장합니다.",
        stats: [["3.1x", "셋업 번들 구매"], ["14k", "매칭 사용"], ["4.9/5", "성능 만족도"]],
        values: [["Setup First", "단품보다 전체 셋업 그림을 먼저 보여줍니다."], ["Latency Focus", "핵심 성능 지표를 짧게 압축합니다."], ["Match Fast", "게임 장르 기준 추천이 빠릅니다."]],
        offers: [["Arc 65", "저지연 키보드", "KRW 189,000"], ["Nebula Pro", "초경량 마우스", "KRW 129,000"], ["Void Arena Pack", "모니터 포함 셋업 번들", "KRW 1,490,000"]],
        tools: [["장비 매칭", "게임 장르와 손 크기에 맞는 장비를 추천합니다."], ["보유 장비 업그레이드", "현재 셋업 기준 병목 요소를 찾습니다."], ["셋업 안내", "호환성과 컬러 조합을 답변합니다."]],
        quote: "성능 수치가 아니라 바로 사고 싶어지는 셋업 장면이 중요했습니다.",
        author: "Commerce Lead / VOID ARC",
        panel: { badge: "Setup Match", title: "내 플레이 스타일용 셋업", text: "주로 하는 게임과 예산을 입력하면 추천 장비 조합과 번들 가격을 보여줍니다.", rows: [["주 장르", "FPS"], ["추천 조합", "Arc 65 + Nebula Pro"], ["예산 맞춤", "KRW 420,000"]], primary: "추천 셋업 담기", secondary: "매칭 보기" },
      },
      {
        id: "ai-saas",
        label: "워크플로우 SaaS",
        company: "SIGNAL GRID",
        mode: "saas",
        nav: ["Platform", "Use Cases", "Demo", "Start"],
        title: "자동화 흐름과 데모 체험을 미래적 UI로 압축한 SaaS 랜딩",
        desc: "유스케이스, 자동화 흐름, 팀 도입 효과, 데모 체험을 네온 대시보드처럼 보여주는 서비스형 페이지입니다.",
        story: "SIGNAL GRID는 AI가 무엇을 할 수 있는지보다 팀이 어떤 병목을 줄이게 되는지를 먼저 설명합니다. 화면은 미래적이지만 메시지는 실무 중심입니다.",
        stats: [["-41%", "반복 작업 감소"], ["2.6x", "승인 속도"], ["18d", "평균 도입 기간"]],
        values: [["Workflow Lens", "복잡한 자동화 흐름을 이해하기 쉽게 나눕니다."], ["Team Proof", "도입 전후 성과 차이를 바로 보여줍니다."], ["Hands-on Demo", "설명보다 체험 버튼을 앞에 둡니다."]],
        offers: [["Ops Board", "작업 큐 자동 분류", "Starter"], ["Approval Flow", "승인 경로 자동화", "Growth"], ["Insight Report", "주간 성과 요약", "Scale"]],
        tools: [["데모 체험", "파일을 넣고 요약·분류 흐름을 즉시 테스트합니다."], ["도입 진단 안내", "팀 규모와 업무 유형 기준 권장 플랜을 제공합니다."], ["자동화 추천", "반복 업무 패턴을 읽고 워크플로우를 제안합니다."]],
        quote: "서비스도 결국 도입 전환을 만드는 화면이 되어야 했습니다.",
        author: "Growth PM / SIGNAL GRID",
        panel: { badge: "Live Demo", title: "팀에 맞는 흐름 진단", text: "팀 규모와 현재 병목을 입력하면 데모 시나리오와 예상 효과를 제안합니다.", rows: [["팀 규모", "12명"], ["주 병목", "승인 지연"], ["추천 플랜", "Growth"]], primary: "데모 시작", secondary: "도입 상담" },
      },
    ],
  },
  {
    id: "collage-paper",
    preview: "collage",
    name: "콜라주 페이퍼",
    en: "Collage Paper",
    badge: "Cut / Layered",
    category: "콘텐츠 감성형 페이지",
    summary: "스티커와 종이 레이어로 인간적인 리듬을 만드는 스타일",
    asset: "mobile-editorial.png",
    theme: { shell: "#f7eee1", surface: "#fffaf1", panel: "#fff8ef", text: "#231a15", muted: "#5b4a3d", accent: "#ffd36e", accentSoft: "#f4bfd5", border: "#e2d0bc", buttonText: "#231a15", shadow: "0 18px 40px rgba(35,26,21,0.12)" },
    industries: [
      {
        id: "indie-bookstore",
        label: "인디 북스토어",
        company: "PAPER NOOK",
        mode: "commerce",
        nav: ["Curations", "New In", "Picks", "Basket"],
        title: "큐레이션과 책 추천 흐름이 살아 있는 독립 서점 페이지",
        desc: "신간 추천, 테마 큐레이션, 에세이 리뷰, 책 추천을 스크랩북처럼 엮은 서점 페이지입니다.",
        story: "PAPER NOOK은 책을 판매하면서도 동시에 취향 편집숍처럼 작동합니다. 고객은 책 제목보다 어떤 분위기의 책인지 먼저 알고 싶어 합니다.",
        stats: [["12k", "월간 큐레이션 조회"], ["54%", "추천 상품 클릭률"], ["4.9/5", "큐레이션 만족도"]],
        values: [["Warm Curation", "책을 장르보다 분위기로 묶어 보여줍니다."], ["Human Notes", "짧은 편집 메모가 신뢰를 만듭니다."], ["Gift Ready", "선물용 추천 흐름이 자연스럽습니다."]],
        offers: [["Weekend Essay Pack", "에세이 3권 큐레이션", "KRW 41,000"], ["City Fiction Shelf", "도시감 소설 셀렉션", "KRW 56,000"], ["Gift Note Wrap", "메모 카드 포함 포장", "KRW 4,000"]],
        tools: [["취향 추천", "좋아하는 영화나 음악 기준으로 책을 추천합니다."], ["책장 조합 제안", "현재 보유 도서와 어울리는 다음 책을 고릅니다."], ["선물 안내", "상대 취향에 맞는 큐레이션을 제안합니다."]],
        quote: "서점도 쇼핑몰보다 편집된 세계처럼 느껴져야 했습니다.",
        author: "Curator / PAPER NOOK",
        panel: { badge: "Reading Basket", title: "이번 주 추천 담기", text: "취향을 고르면 큐레이터 메모와 함께 세 권 구성을 추천합니다.", rows: [["선호 무드", "조용한 도시"], ["추천 큐레이션", "City Fiction Shelf"], ["포장 옵션", "Gift Note Wrap"]], primary: "추천 세트 담기", secondary: "추천 받기" },
      },
      {
        id: "stationery-shop",
        label: "스테이셔너리 숍",
        company: "CUT & NOTE",
        mode: "commerce",
        nav: ["Collections", "Gift Sets", "Match", "Cart"],
        title: "종이 질감과 선물 구성을 한눈에 보여주는 문구 편집숍 페이지",
        desc: "노트, 스티커, 펜, 선물세트, 조합 추천을 손으로 붙여 만든 듯한 화면에 담았습니다.",
        story: "CUT & NOTE는 제품 단품보다 조합이 중요한 문구 숍입니다. 서로 어울리는 톤과 패턴을 함께 보여줄수록 구매가 쉬워집니다.",
        stats: [["63%", "세트 구매 비중"], ["8.4k", "조합 추천 사용"], ["4.8/5", "선물 만족도"]],
        values: [["Layered Display", "소재와 패턴의 조합을 먼저 보여줍니다."], ["Gift Focus", "선물 박스 구성이 직관적입니다."], ["Visual Pairing", "노트와 펜, 스티커를 한 번에 묶습니다."]],
        offers: [["Daily Desk Set", "노트 + 펜 + 스티커", "KRW 28,000"], ["Archive Notebook", "두께감 있는 무지 노트", "KRW 17,000"], ["Mood Tape Pack", "컬러 마스킹 테이프 세트", "KRW 12,000"]],
        tools: [["조합 추천", "좋아하는 색감 기준으로 세트를 제안합니다."], ["보유 문구 매칭", "이미 가지고 있는 도구와 어울리는 제품을 고릅니다."], ["선물 안내", "예산과 대상별 선물 구성을 추천합니다."]],
        quote: "같이 사면 더 좋아 보이는 조합을 화면에서 먼저 보여주고 싶었습니다.",
        author: "Founder / CUT & NOTE",
        panel: { badge: "Gift Builder", title: "선물 세트 바로 구성", text: "대상과 예산을 선택하면 포장 포함 추천 구성을 보여줍니다.", rows: [["대상", "직장 동료"], ["예산", "KRW 30,000"], ["추천 세트", "Daily Desk Set"]], primary: "세트 담기", secondary: "조합 보기" },
      },
      {
        id: "local-cafe",
        label: "동네 카페 브랜드",
        company: "TABLE WARM",
        mode: "booking",
        nav: ["Menu", "Space", "Pairing", "Reserve"],
        title: "시그니처 메뉴와 공간 분위기를 함께 파는 동네 카페 페이지",
        desc: "메뉴 소개, 좌석 분위기, 원두 스토리, 페어링 추천, 예약 문의를 감성적인 콜라주로 연결했습니다.",
        story: "TABLE WARM은 커피보다 머무르는 시간을 판매하는 브랜드입니다. 그래서 메뉴보다 먼저 공간과 취향 큐레이션이 보이도록 설계합니다.",
        stats: [["4.9/5", "공간 만족도"], ["31%", "시그니처 세트 주문"], ["2.4x", "예약 문의 증가"]],
        values: [["Place First", "카페가 가진 분위기를 먼저 전합니다."], ["Menu Pairing", "디저트와 음료를 함께 제안합니다."], ["Local Tone", "동네 브랜드다운 다정한 말투를 유지합니다."]],
        offers: [["Cream Salt Latte", "시그니처 음료", "KRW 6,500"], ["Warm Butter Scone", "가장 인기 있는 페어링", "KRW 4,800"], ["Window Seat Booking", "촬영·소모임 예약", "Consultation"]],
        tools: [["페어링 추천", "기분과 시간대에 맞는 음료 조합을 제안합니다."], ["좌석 추천", "혼자 작업, 대화, 모임 목적별 자리를 안내합니다."], ["예약 안내", "촬영 가능 시간과 대관 범위를 답변합니다."]],
        quote: "메뉴판이 아니라 공간의 기억을 파는 페이지가 필요했습니다.",
        author: "Owner / TABLE WARM",
        panel: { badge: "Cafe Reserve", title: "좌석과 메뉴 미리 선택", text: "방문 목적과 인원 수를 넣으면 추천 좌석과 시그니처 조합을 안내합니다.", rows: [["방문 목적", "작업"], ["추천 좌석", "창가 2인석"], ["추천 메뉴", "Cream Salt Latte"]], primary: "예약 문의", secondary: "페어링 보기" },
      },
    ],
  },
  {
    id: "grain-editorial",
    preview: "grain",
    name: "그레인 에디토리얼",
    en: "Grain Editorial",
    badge: "Mood / Depth",
    category: "분위기 집중형 페이지",
    summary: "입자감과 여백으로 무드를 깊게 남기는 스타일",
    asset: "mobile-editorial.png",
    theme: { shell: "#e3d8cb", surface: "#f6efe6", panel: "rgba(255,255,255,0.38)", text: "#2d241d", muted: "#65584d", accent: "#7c6352", accentSoft: "#d9cab7", border: "rgba(73,53,38,0.18)", buttonText: "#ffffff", shadow: "0 22px 48px rgba(45,36,29,0.12)" },
    industries: [
      {
        id: "boutique-hotel",
        label: "부티크 호텔",
        company: "HOTEL STILL",
        mode: "booking",
        nav: ["Stay", "Rooms", "Planner", "Reserve"],
        title: "객실 무드와 체류 경험을 깊게 남기는 부티크 호텔 페이지",
        desc: "객실 타입, 계절별 패키지, 동네 가이드, 여행 플래너, 예약 전환을 에디토리얼 무드로 담은 페이지입니다.",
        story: "HOTEL STILL은 침대를 파는 곳이 아니라 머무는 분위기를 파는 브랜드입니다. 객실 정보는 정확하게, 무드는 더 길게 남도록 설계합니다.",
        stats: [["89%", "주말 예약률"], ["4.9/5", "숙박 만족도"], ["36%", "패키지 업셀"]],
        values: [["Slow Luxury", "급하지 않은 톤으로 프리미엄을 만듭니다."], ["Editorial Flow", "스토리 읽듯 숙박 정보를 탐색하게 합니다."], ["Stay Planning", "체류 일정까지 연결합니다."]],
        offers: [["Studio Room", "도심형 기본 객실", "From KRW 240,000"], ["Still Suite", "테라스 포함 스위트", "From KRW 420,000"], ["Weekend Package", "조식 + 동네 가이드", "From KRW 310,000"]],
        tools: [["여행 플래너", "체류 일정과 취향을 바탕으로 동네 코스를 제안합니다."], ["객실 매칭", "여행 목적에 맞는 객실 타입을 추천합니다."], ["예약 안내", "체크인, 주차, 추가 요청을 답변합니다."]],
        quote: "예약 전에 이미 머물고 싶은 기분이 들어야 했습니다.",
        author: "Brand Manager / HOTEL STILL",
        panel: { badge: "Stay Planner", title: "이번 여행에 맞는 객실 찾기", text: "방문 목적과 인원, 원하는 무드를 입력하면 추천 객실과 패키지를 제안합니다.", rows: [["방문 목적", "주말 휴식"], ["추천 객실", "Still Suite"], ["추천 패키지", "Weekend Package"]], primary: "예약하기", secondary: "일정 보기" },
      },
      {
        id: "perfume-house",
        label: "니치 퍼퓸 하우스",
        company: "MOSS & AMBER",
        mode: "commerce",
        nav: ["Scents", "Discovery", "Notes", "Shop"],
        title: "향의 서사와 추천 흐름을 품위 있게 묶은 니치 퍼퓸 페이지",
        desc: "향 노트, 시향 키트, 브랜드 스토리, 향 추천, 구매 흐름을 깊은 톤으로 정리한 페이지입니다.",
        story: "MOSS & AMBER는 향을 설명하는 대신 기억을 불러오는 단어를 고릅니다. 각 제품이 가진 장면과 노트를 함께 전달하는 것이 중요합니다.",
        stats: [["71%", "디스커버리 키트 전환"], ["4.8/5", "향 추천 만족도"], ["29%", "본품 추가 구매"]],
        values: [["Narrative Scent", "향을 이미지와 장면으로 설명합니다."], ["Quiet Premium", "과장 대신 정제된 신뢰감을 만듭니다."], ["Trial First", "시향 키트 전환을 자연스럽게 연결합니다."]],
        offers: [["Amber Room", "우디 앰버 시그니처", "KRW 189,000"], ["Moss Rain", "그린·어싱 계열", "KRW 182,000"], ["Discovery Set", "5종 시향 키트", "KRW 39,000"]],
        tools: [["향 추천", "좋아하는 공간과 계절감 기준으로 향을 제안합니다."], ["가지고 있는 향 분석", "보유 향수와 겹치지 않는 방향을 골라줍니다."], ["시향 안내", "노트 차이와 레이어링 팁을 알려줍니다."]],
        quote: "설명문이 아니라 장면을 떠올리게 하는 페이지를 원했습니다.",
        author: "Creative Director / MOSS & AMBER",
        panel: { badge: "Scent Match", title: "내 무드에 맞는 향 찾기", text: "선호하는 공간과 시간대를 선택하면 추천 향과 시향 키트를 보여줍니다.", rows: [["선호 무드", "비 오는 저녁"], ["추천 향", "Moss Rain"], ["입문 옵션", "Discovery Set"]], primary: "시향 키트 담기", secondary: "향 추천" },
      },
      {
        id: "interior-studio",
        label: "주거 인테리어 스튜디오",
        company: "ROOM INDEX",
        mode: "consulting",
        nav: ["Projects", "Mood", "Layout", "Contact"],
        title: "집의 분위기와 설계 과정을 깊게 보여주는 주거 인테리어 페이지",
        desc: "프로젝트 사진, 스타일 무드, 예산 가이드, 배치 제안, 상담 문의를 여백 중심으로 정리했습니다.",
        story: "ROOM INDEX는 완성 사진만 아름답게 보여주는 대신 고객이 자신의 집에 어떤 변화가 생길지 상상하게 합니다. 감정과 실용을 같이 전달하는 방식입니다.",
        stats: [["54", "완료 주거 프로젝트"], ["3.1x", "문의 체류 시간"], ["88%", "상담 후 계약 전환"]],
        values: [["Mood First", "집이 주는 감정을 먼저 전합니다."], ["Practical Guide", "예산과 범위를 숨기지 않습니다."], ["Visual Trust", "사례 사진이 자연스럽게 신뢰를 만듭니다."]],
        offers: [["Living Refresh", "거실 중심 리디자인", "Proposal"], ["Full Renewal", "전체 리노베이션", "Proposal"], ["Mood Consultation", "스타일링 진단", "KRW 350,000"]],
        tools: [["레이아웃 제안", "현재 집 사진 위에 가구 배치를 추천합니다."], ["무드 매칭", "좋아하는 분위기와 예산에 맞는 방향을 찾습니다."], ["상담 안내", "공사 범위와 예상 일정 질문에 답합니다."]],
        quote: "상담 전에도 이미 우리 집이 어떻게 바뀔지 보였으면 했습니다.",
        author: "Founder / ROOM INDEX",
        panel: { badge: "Layout Brief", title: "우리 집 상담 보내기", text: "공간 사진과 원하는 분위기를 넣으면 초기 방향과 상담 범위를 제안합니다.", rows: [["공간", "거실 + 다이닝"], ["무드", "Soft Warm"], ["예산", "KRW 30M - 45M"]], primary: "상담 문의", secondary: "배치 보기" },
      },
    ],
  },
  {
    id: "handcrafted-note",
    preview: "hand",
    name: "핸드크래프트 노트",
    en: "Handcrafted Note",
    badge: "Warm / Handmade",
    category: "친밀감 강화형 페이지",
    summary: "손글씨와 낙서 같은 요소로 브랜드를 더 가깝게 만드는 스타일",
    asset: "hero-studio.png",
    theme: { shell: "#fff8e7", surface: "#fffef7", panel: "#fff8ef", text: "#342519", muted: "#664f3e", accent: "#ffcf66", accentSoft: "#d5ebff", border: "#342519", buttonText: "#342519", shadow: "5px 5px 0 #342519" },
    industries: [
      {
        id: "kids-art",
        label: "키즈 아트 스튜디오",
        company: "DOODLE CAMP",
        mode: "booking",
        nav: ["Programs", "Teachers", "Match", "Book"],
        title: "아이 성향과 수업 분위기를 따뜻하게 보여주는 키즈 아트 스튜디오 페이지",
        desc: "연령별 클래스, 선생님 소개, 수업 추천, 체험 예약을 손그림 같은 화면 안에 담았습니다.",
        story: "DOODLE CAMP는 부모가 수업 커리큘럼보다도 분위기와 아이의 적합도를 먼저 보게 된다는 점에서 출발합니다. 그래서 설명보다 안심을 먼저 설계합니다.",
        stats: [["240+", "월간 체험 수업"], ["84%", "체험 후 등록률"], ["4.9/5", "학부모 만족도"]],
        values: [["Friendly Tone", "낯설지 않고 다정한 인상을 줍니다."], ["Kid Fit", "아이의 성향 기준으로 반을 추천합니다."], ["Easy Booking", "체험 신청 흐름을 단순하게 만듭니다."]],
        offers: [["Color Lab", "5-7세 감각 미술", "KRW 160,000/mo"], ["Story Canvas", "8-10세 표현 수업", "KRW 180,000/mo"], ["Weekend Trial", "주말 체험 클래스", "KRW 25,000"]],
        tools: [["반 추천", "아이 성향과 집중 시간에 맞춰 반을 추천합니다."], ["작품 기록 리포트", "수업 후 아이의 표현 특징을 요약합니다."], ["상담 안내", "준비물과 시간표를 바로 안내합니다."]],
        quote: "부모가 안심하고 체험 신청할 수 있는 분위기가 가장 중요했습니다.",
        author: "Director / DOODLE CAMP",
        panel: { badge: "Trial Booking", title: "체험 반 고르기", text: "연령과 아이 성향을 넣으면 맞는 반과 가능한 시간을 추천합니다.", rows: [["연령", "7세"], ["추천 수업", "Color Lab"], ["가능 시간", "토요일 11:00"]], primary: "체험 예약", secondary: "반 추천" },
      },
      {
        id: "pet-bakery",
        label: "펫 베이커리",
        company: "PAW CRUMB",
        mode: "commerce",
        nav: ["Treats", "Custom Cake", "Match", "Cart"],
        title: "반려견의 취향과 건강 상태를 같이 고려하는 펫 베이커리 페이지",
        desc: "간식, 맞춤 케이크, 원재료 안내, 추천, 주문 흐름을 따뜻한 수제 감성으로 묶었습니다.",
        story: "PAW CRUMB은 맛있는 간식을 파는 곳이지만 보호자 입장에서는 알레르기와 기호성 정보가 더 중요합니다. 그래서 귀여움과 신뢰를 같이 보여줍니다.",
        stats: [["4.9/5", "기호성 만족도"], ["37%", "맞춤 케이크 비중"], ["9.2k", "추천 사용"]],
        values: [["Warm Trust", "수제 감성을 유지하면서도 정보는 분명하게 제공합니다."], ["Pet Fit", "반려견 상태에 맞는 옵션을 제안합니다."], ["Giftable", "생일과 기념일 구매 흐름이 자연스럽습니다."]],
        offers: [["Sweet Potato Bites", "저알레르기 간식", "KRW 12,000"], ["Birthday Bone Cake", "이름 각인 가능", "KRW 36,000"], ["Puppy Trial Box", "첫 주문 샘플 박스", "KRW 18,000"]],
        tools: [["간식 추천", "나이와 알레르기 정보를 기준으로 추천합니다."], ["생일 케이크 커스텀", "문구와 컬러 테마를 바로 시뮬레이션합니다."], ["상담 안내", "급여량과 보관 방법을 안내합니다."]],
        quote: "귀여운 것만으로는 부족했고 보호자가 안심할 정보가 필요했습니다.",
        author: "Founder / PAW CRUMB",
        panel: { badge: "Pet Match", title: "우리 강아지용 추천 받기", text: "품종과 나이, 알레르기 정보를 입력하면 맞는 간식과 케이크 옵션을 제안합니다.", rows: [["품종", "비숑 / 3살"], ["추천 간식", "Sweet Potato Bites"], ["기념일 옵션", "Birthday Bone Cake"]], primary: "추천 상품 담기", secondary: "간식 추천" },
      },
      {
        id: "artisan-bakery",
        label: "아티장 베이커리",
        company: "OVEN LETTER",
        mode: "commerce",
        nav: ["Bread", "Seasonal", "Pairing", "Order"],
        title: "빵의 온기와 예약 주문 흐름을 함께 보여주는 동네 베이커리 페이지",
        desc: "시그니처 빵, 시즌 메뉴, 픽업 예약, 페어링 추천을 손글씨 메모 같은 톤으로 구성했습니다.",
        story: "OVEN LETTER는 매일 굽는 빵의 표정과 가게 분위기를 함께 전하는 베이커리입니다. 메뉴를 넘어 하루의 선택지가 되도록 구성합니다.",
        stats: [["6:30", "첫 구움 시작"], ["72%", "예약 픽업 비중"], ["4.8/5", "재방문 만족도"]],
        values: [["Daily Fresh", "오늘 나온 빵이 가장 먼저 보입니다."], ["Neighborhood Tone", "동네 가게다운 다정함을 유지합니다."], ["Easy Pickup", "예약 픽업 흐름이 간단합니다."]],
        offers: [["Butter Salt Roll", "가장 인기 있는 시그니처", "KRW 3,800"], ["Milk Cream Loaf", "오후 한정 메뉴", "KRW 6,200"], ["Weekend Brunch Box", "빵 + 잼 + 스프레드", "KRW 19,000"]],
        tools: [["페어링 추천", "커피나 차 취향에 맞는 빵 조합을 추천합니다."], ["남은 수량 알림", "품절 임박 메뉴를 바로 안내합니다."], ["픽업 예약 도우미", "방문 시간에 맞춰 갓 나온 메뉴를 제안합니다."]],
        quote: "주문 전에 이미 가게 냄새가 떠오르는 페이지가 되고 싶었습니다.",
        author: "Owner Baker / OVEN LETTER",
        panel: { badge: "Pickup Order", title: "오늘 픽업 예약", text: "방문 시간과 선호 메뉴를 고르면 맞는 구움 시간과 추천 세트를 안내합니다.", rows: [["방문 시간", "오늘 17:30"], ["추천 메뉴", "Milk Cream Loaf"], ["세트 추천", "Weekend Brunch Box"]], primary: "픽업 주문", secondary: "페어링 보기" },
      },
    ],
  },
  {
    id: "organic-soft",
    preview: "organic",
    name: "오가닉 소프트",
    en: "Organic Soft",
    badge: "Soft / Human",
    category: "유연한 브랜드형 페이지",
    summary: "곡선과 여백으로 편안하고 인간적인 브랜드 인상을 만드는 스타일",
    asset: "mobile-editorial.png",
    theme: { shell: "#eef5e6", surface: "#f9fcf4", panel: "rgba(255,255,255,0.76)", text: "#25311f", muted: "#596855", accent: "#9bc977", accentSoft: "#ffd6b3", border: "rgba(37,49,31,0.14)", buttonText: "#25311f", shadow: "0 18px 42px rgba(37,49,31,0.10)" },
    industries: [
      {
        id: "furniture-store",
        label: "라이프스타일 가구 스토어",
        company: "MOSS HOME",
        mode: "commerce",
        nav: ["Furniture", "Rooms", "Layout", "Cart"],
        title: "집 분위기와 배치 경험을 먼저 보여주는 라이프스타일 가구 스토어",
        desc: "가구 컬렉션, 룸별 큐레이션, 배치 미리보기, 구매 흐름을 부드러운 곡선 UI로 구성했습니다.",
        story: "MOSS HOME은 제품 스펙보다 집의 분위기를 먼저 제안하는 가구 브랜드입니다. 가구를 사는 일이 아니라 공간을 고르는 경험으로 보이게 합니다.",
        stats: [["2.7x", "배치 보기 사용"], ["46%", "세트 구매 비중"], ["4.8/5", "배송 만족도"]],
        values: [["Room First", "제품보다 공간 장면을 먼저 보여줍니다."], ["Soft Trust", "큰 금액의 구매를 편안한 톤으로 유도합니다."], ["Set Curation", "단품보다 조합 구매를 쉽게 만듭니다."]],
        offers: [["Moss Sofa", "3인 패브릭 소파", "KRW 1,690,000"], ["Pebble Table", "유기형 라운드 테이블", "KRW 620,000"], ["Quiet Living Set", "소파 + 테이블 구성", "KRW 2,120,000"]],
        tools: [["배치 미리보기", "집 사진 위에 가구를 올려 배치를 확인합니다."], ["무드별 추천", "원하는 집 분위기에 맞는 컬렉션을 제안합니다."], ["사이즈 안내", "동선과 치수를 기준으로 적합도를 알려줍니다."]],
        quote: "가구보다 집이 바뀌는 장면이 먼저 보여야 했습니다.",
        author: "Brand Lead / MOSS HOME",
        panel: { badge: "Room Planner", title: "우리 집용 배치 먼저 보기", text: "거실 사진과 선호 무드를 넣으면 추천 가구와 배치 구성을 제안합니다.", rows: [["공간", "거실 4.2m"], ["추천 세트", "Quiet Living Set"], ["추천 무드", "Soft Natural"]], primary: "배치 미리보기", secondary: "컬렉션 보기" },
      },
      {
        id: "wellness-retreat",
        label: "웰니스 리트릿",
        company: "BREATHE LAND",
        mode: "booking",
        nav: ["Programs", "Stays", "Match", "Book"],
        title: "휴식 목적에 따라 프로그램을 매칭해주는 웰니스 리트릿 페이지",
        desc: "숙박형 프로그램, 식단, 일정표, 코스 추천, 예약 상담을 편안한 호흡감으로 연결한 페이지입니다.",
        story: "BREATHE LAND는 예약 버튼보다 먼저 느슨해지는 기분을 주어야 하는 브랜드입니다. 동시에 일정과 비용은 불안하지 않게 또렷해야 합니다.",
        stats: [["4.9/5", "만족도"], ["67%", "재방문 의향"], ["3.3x", "상담 체류 시간"]],
        values: [["Calm Pace", "서두르지 않는 흐름으로 브랜드 톤을 만듭니다."], ["Program Fit", "목적에 따라 코스를 나눕니다."], ["Clear Booking", "예약과 준비 정보를 쉽게 보여줍니다."]],
        offers: [["Weekend Reset", "2박 3일 휴식 코스", "From KRW 480,000"], ["Deep Sleep Retreat", "수면 회복 집중 코스", "From KRW 620,000"], ["Private Healing", "1:1 맞춤 프로그램", "Consultation"]],
        tools: [["코스 추천", "피로도와 원하는 회복 포인트 기준으로 코스를 추천합니다."], ["식단 매칭", "선호 식단과 알레르기를 반영합니다."], ["예약 안내", "준비물과 픽업 안내를 제공합니다."]],
        quote: "설명보다도 숨이 조금 느려지는 화면이 필요했습니다.",
        author: "Program Director / BREATHE LAND",
        panel: { badge: "Retreat Match", title: "지금 필요한 리트릿 찾기", text: "컨디션과 원하는 회복 방향을 입력하면 맞는 코스와 일정을 제안합니다.", rows: [["현재 상태", "수면 부족"], ["추천 코스", "Deep Sleep Retreat"], ["예약 가능", "다음 주 금요일"]], primary: "상담 예약", secondary: "코스 보기" },
      },
      {
        id: "eco-living",
        label: "에코 리빙 셀렉트숍",
        company: "ROOT SUPPLY",
        mode: "commerce",
        nav: ["Shop", "Bundles", "Home Match", "Subscribe"],
        title: "지속가능한 생활용품을 생활 맥락으로 묶어 보여주는 셀렉트숍 페이지",
        desc: "친환경 제품, 정기배송, 번들 구성, 홈 매칭 추천을 부드러운 라이프스타일 톤으로 정리했습니다.",
        story: "ROOT SUPPLY는 친환경이라는 말만 반복하지 않습니다. 어떤 집과 어떤 습관에 잘 맞는지 구체적으로 보여주는 것이 더 중요합니다.",
        stats: [["58%", "정기배송 유지율"], ["2.2x", "번들 구매"], ["4.8/5", "제품 만족도"]],
        values: [["Habit Based", "제품보다 생활 루틴과 함께 보여줍니다."], ["Home Match", "집 분위기와 쓰임새를 같이 고려합니다."], ["Soft Commerce", "부담 없는 전환 흐름을 유지합니다."]],
        offers: [["Kitchen Reset Pack", "주방 소모품 번들", "KRW 28,000"], ["Gentle Laundry Kit", "세탁·탈취 세트", "KRW 34,000"], ["Monthly Home Care", "정기배송 플랜", "KRW 22,000/mo"]],
        tools: [["홈 매칭", "집 분위기와 가족 구성에 맞는 제품을 추천합니다."], ["보유 제품 체크", "중복 구매 없이 필요한 품목만 정리합니다."], ["정기배송 안내", "주기와 구성 변경을 빠르게 도와줍니다."]],
        quote: "좋은 가치만이 아니라 바로 써보고 싶은 실용성이 보여야 했습니다.",
        author: "Curation Lead / ROOT SUPPLY",
        panel: { badge: "Home Match", title: "우리 집용 번들 찾기", text: "공간과 가족 구성을 입력하면 맞는 번들과 정기배송 옵션을 제안합니다.", rows: [["공간", "2인 가구 아파트"], ["추천 번들", "Kitchen Reset Pack"], ["정기배송", "월 1회"]], primary: "번들 담기", secondary: "추천 보기" },
      },
    ],
  },
  {
    id: "playful-type",
    preview: "playful",
    name: "플레이풀 타이포",
    en: "Playful Type",
    badge: "Big / Fun",
    category: "타이포 주도형 페이지",
    summary: "문자 자체를 시각 요소로 써서 기억에 남게 만드는 스타일",
    asset: "style-compare.png",
    theme: { shell: "#fff4ae", surface: "#fff8d4", panel: "#ffffff", text: "#111827", muted: "#4a5565", accent: "#0f3bd9", accentSoft: "#ff79b0", border: "#111827", buttonText: "#ffffff", shadow: "0 16px 36px rgba(17,24,39,0.16)" },
    industries: [
      {
        id: "youth-fashion",
        label: "영 타깃 패션 스토어",
        company: "BOP BOP",
        mode: "commerce",
        nav: ["New", "Looks", "Style", "Cart"],
        title: "룩 조합과 스타일 미리보기을 크게 밀어주는 영 타깃 패션 페이지",
        desc: "신상품, 스타일 룩북, 스타일 미리보기, 장바구니 전환을 큰 타이포 중심으로 정리한 패션 커머스입니다.",
        story: "BOP BOP은 옷의 디테일보다 먼저 입었을 때의 태도를 보여줍니다. 그래서 룩 조합과 컬러 리듬이 화면 전면에 나오게 만듭니다.",
        stats: [["21k", "스타일 비교 사용"], ["3.4x", "룩북 클릭"], ["48%", "코디 세트 구매"]],
        values: [["Look First", "제품보다 착장 전체를 먼저 보여줍니다."], ["Big Energy", "브랜드 목소리를 크게 전달합니다."], ["Pair Shopping", "혼자 사는 것보다 같이 담게 만듭니다."]],
        offers: [["Bop Denim", "와이드 데님 팬츠", "KRW 78,000"], ["Flash Zip Hoodie", "오버핏 후디", "KRW 69,000"], ["Campus Set", "후디 + 팬츠 구성", "KRW 129,000"]],
        tools: [["스타일 미리보기", "룩 조합을 화면에서 비교할 수 있습니다."], ["옷장 매칭", "가지고 있는 옷과 어울리는 신상품을 추천합니다."], ["사이즈 안내", "브랜드별 핏 차이를 쉽게 설명합니다."]],
        quote: "화면만 봐도 이 브랜드를 입은 기분이 들어야 했습니다.",
        author: "Creative Lead / BOP BOP",
        panel: { badge: "Style Studio", title: "내 옷장 기준 추천 받기", text: "사진과 선호 핏을 넣으면 스타일 미리보기와 함께 추천 코디를 제안합니다.", rows: [["선호 핏", "와이드"], ["추천 코디", "Campus Set"], ["추천 사이즈", "M"]], primary: "스타일 비교 시작", secondary: "코디 담기" },
      },
      {
        id: "event-merch",
        label: "이벤트 굿즈 스토어",
        company: "FAN BLAST",
        mode: "commerce",
        nav: ["Drop", "Bundles", "Gift", "Cart"],
        title: "굿즈 드롭과 팬심 번들을 직관적으로 밀어주는 이벤트 페이지",
        desc: "한정 굿즈, 번들 패키지, 굿즈 추천, 장바구니 흐름을 큼직한 타이포와 강한 색 대비로 설계했습니다.",
        story: "FAN BLAST는 정보보다 열기를 먼저 보여줘야 하는 굿즈 스토어입니다. 팬이 바로 들어와 한정 수량과 조합을 판단할 수 있어야 합니다.",
        stats: [["79%", "드롭 당일 품절"], ["2.7x", "번들 구매"], ["15k", "알림 신청"]],
        values: [["Launch Heat", "드롭 순간의 속도를 화면에 반영합니다."], ["Bundle Push", "팬이 원하는 묶음을 먼저 제안합니다."], ["Gift Ready", "친구 선물 구매 흐름도 단순하게 만듭니다."]],
        offers: [["Cheer Pack", "응원봉 + 스티커 세트", "KRW 39,000"], ["Stage Tee", "한정 프린트 티셔츠", "KRW 48,000"], ["Fan Box", "포토카드 포함 풀세트", "KRW 82,000"]],
        tools: [["굿즈 추천", "좋아하는 멤버나 테마 기준 구성 추천"], ["보유 굿즈 분석", "이미 가진 품목과 겹치지 않게 추천"], ["알림 안내", "드롭 시작과 수량 마감 상황을 안내"]],
        quote: "팬이 고민하지 않고 바로 담을 수 있게 속도를 만들고 싶었습니다.",
        author: "Merch Manager / FAN BLAST",
        panel: { badge: "Drop Timer", title: "지금 가장 인기 있는 번들", text: "드롭 남은 시간과 선호 테마를 바탕으로 추천 번들을 먼저 보여줍니다.", rows: [["남은 수량", "124개"], ["추천 번들", "Fan Box"], ["추가 혜택", "포토카드 2장"]], primary: "번들 구매", secondary: "추천 보기" },
      },
      {
        id: "language-bootcamp",
        label: "스피킹 부트캠프",
        company: "SPEAK UP",
        mode: "booking",
        nav: ["Programs", "Coaches", "Test", "Enroll"],
        title: "학습 의욕을 끌어올리는 스피킹 부트캠프 소개 페이지",
        desc: "과정 소개, 코치 스타일, 레벨 테스트, 수강 등록 흐름을 활기 있는 타이포 중심으로 구성했습니다.",
        story: "SPEAK UP은 공부 서비스라기보다 에너지를 밀어주는 프로그램입니다. 학습자가 바로 시작하고 싶게 만드는 말투와 리듬이 중요합니다.",
        stats: [["3주", "첫 실전 말하기 체감"], ["92%", "수강 지속률"], ["4.8/5", "코칭 만족도"]],
        values: [["Momentum", "시작 장벽을 낮추고 의욕을 올립니다."], ["Coach Match", "학습 성향에 맞는 코치를 연결합니다."], ["Quick Win", "초기 성취감을 빨리 보여줍니다."]],
        offers: [["Kickstart 21", "3주 집중 코스", "KRW 290,000"], ["Daily Talk", "매일 20분 코칭", "KRW 360,000"], ["Interview Boost", "면접 특화 과정", "KRW 420,000"]],
        tools: [["레벨 테스트", "짧은 말하기 샘플로 현재 수준을 진단합니다."], ["오답 패턴 분석", "자주 막히는 문장을 찾아줍니다."], ["학습 안내", "복습 일정과 표현 추천을 제공합니다."]],
        quote: "설명보다 먼저 말해보고 싶어지는 기분을 만드는 게 목표였습니다.",
        author: "Learning Lead / SPEAK UP",
        panel: { badge: "Level Check", title: "내 레벨로 시작하기", text: "목표와 현재 수준을 선택하면 추천 과정과 코칭 빈도를 제안합니다.", rows: [["목표", "면접 대비"], ["추천 과정", "Interview Boost"], ["추천 빈도", "주 4회"]], primary: "레벨 테스트 시작", secondary: "과정 등록" },
      },
    ],
  },
  {
    id: "chrome-luxe",
    preview: "chrome",
    name: "크롬 럭스",
    en: "Chrome Luxe",
    badge: "Gloss / Premium",
    category: "프리미엄 전환형 페이지",
    summary: "반사감과 매끈한 표면으로 미래적 프리미엄을 만드는 스타일",
    asset: "hero-studio.png",
    theme: { shell: "#d8dfe9", surface: "#eef3f8", panel: "rgba(255,255,255,0.58)", text: "#0f172a", muted: "#556173", accent: "#161d27", accentSoft: "#ffffff", border: "rgba(255,255,255,0.68)", buttonText: "#ffffff", shadow: "0 24px 64px rgba(15,23,42,0.14)" },
    industries: [
      {
        id: "jewelry-brand",
        label: "파인 주얼리 브랜드",
        company: "LUNE FORM",
        mode: "commerce",
        nav: ["Collections", "Bespoke", "Match", "Shop"],
        title: "제품 디테일과 맞춤 상담을 고급스럽게 이어주는 주얼리 페이지",
        desc: "컬렉션, 소재 설명, 커스텀 옵션, 추천, 구매·상담 흐름을 차갑고 매끈한 톤으로 설계했습니다.",
        story: "LUNE FORM은 제품 사진만으로 끝나는 브랜드가 아닙니다. 착용 맥락과 기념일, 커스텀 상담까지 매끄럽게 이어지는 흐름이 중요합니다.",
        stats: [["58%", "맞춤 상담 전환"], ["4.9/5", "구매 만족도"], ["31%", "세트 업셀"]],
        values: [["Luxury Surface", "제품의 질감과 반사감을 중심에 둡니다."], ["Bespoke Flow", "커스텀 상담 진입이 자연스럽습니다."], ["Gift Confidence", "선물 구매도 쉽게 만듭니다."]],
        offers: [["Moon Line Ring", "18K 화이트 골드", "KRW 780,000"], ["Lune Drop Earrings", "다이아 세팅", "KRW 1,290,000"], ["Bespoke Bridal Set", "맞춤 제작 상담", "Consultation"]],
        tools: [["착용 추천", "손 모양과 피부 톤 기준 디자인을 추천합니다."], ["기존 보유 제품 매칭", "가지고 있는 주얼리와 어울리는 세트를 제안합니다."], ["상담 안내", "소재, 각인, 제작 기간을 안내합니다."]],
        quote: "고급스러움은 제품보다 흐름에서 먼저 느껴진다고 생각했습니다.",
        author: "Brand Director / LUNE FORM",
        panel: { badge: "Bespoke Desk", title: "맞춤 상담 시작", text: "예산과 착용 목적을 넣으면 추천 컬렉션과 상담 옵션을 제안합니다.", rows: [["착용 목적", "기념일 선물"], ["추천 컬렉션", "Moon Line"], ["상담 형태", "온라인 1:1"]], primary: "상담 예약", secondary: "컬렉션 보기" },
      },
      {
        id: "device-store",
        label: "프리미엄 디바이스 스토어",
        company: "SILVER SIGNAL",
        mode: "commerce",
        nav: ["Devices", "Bundles", "Setup", "Cart"],
        title: "프리미엄 디바이스와 셋업 번들을 미래적으로 보여주는 스토어 페이지",
        desc: "디바이스 성능, 번들 제안, 셋업 추천, 장바구니 흐름을 반사감 있는 UI로 정리했습니다.",
        story: "SILVER SIGNAL은 스펙을 나열하기보다 제품이 책상 위에서 어떤 인상을 만드는지까지 보여주는 스토어입니다. 기술과 라이프스타일을 동시에 판매합니다.",
        stats: [["2.5x", "번들 구매"], ["16k", "셋업 사용"], ["4.8/5", "제품 만족도"]],
        values: [["Premium Tech", "제품의 고급감을 비주얼로 증폭합니다."], ["Desk Setup", "단품보다 셋업 장면을 먼저 보여줍니다."], ["Fast Choice", "비교 포인트를 짧게 제시합니다."]],
        offers: [["Signal Pad", "크리에이터용 태블릿", "KRW 1,190,000"], ["Arc Monitor", "5K 스튜디오 디스플레이", "KRW 1,790,000"], ["Desk Signal Bundle", "모니터 + 태블릿 구성", "KRW 2,740,000"]],
        tools: [["셋업 추천", "작업 방식에 맞는 디바이스 조합을 제안합니다."], ["보유 장비 호환성 체크", "현재 장비와의 연결성을 분석합니다."], ["구매 안내", "색상, 포트, 배송 일정을 안내합니다."]],
        quote: "기술 제품도 결국 갖고 싶게 만드는 장면이 먼저여야 했습니다.",
        author: "Commerce PM / SILVER SIGNAL",
        panel: { badge: "Setup Guide", title: "내 작업용 조합 찾기", text: "직업과 예산을 입력하면 추천 디바이스와 번들을 바로 제안합니다.", rows: [["주 작업", "영상 편집"], ["추천 조합", "Arc Monitor + Signal Pad"], ["예산 범위", "KRW 3M 이하"]], primary: "추천 조합 담기", secondary: "셋업 보기" },
      },
      {
        id: "fitness-club",
        label: "프리미엄 피트니스 클럽",
        company: "VELOCITY ONE",
        mode: "membership",
        nav: ["Club", "Programs", "Match", "Join"],
        title: "시설, 코칭, 멤버십 가치를 세련되게 압축한 피트니스 클럽 페이지",
        desc: "시설 소개, 코치 프로그램, 코스 추천, 멤버십 등록 흐름을 고급스럽고 강하게 보여주는 페이지입니다.",
        story: "VELOCITY ONE은 헬스장이 아니라 퍼포먼스 라이프스타일 클럽처럼 보이도록 설계합니다. 시설 퀄리티와 맞춤 코칭의 가치가 동시에 읽혀야 합니다.",
        stats: [["4.9/5", "시설 만족도"], ["76%", "PT 전환률"], ["2.2x", "멤버십 문의 증가"]],
        values: [["Premium Access", "시설과 혜택을 짧게 강하게 보여줍니다."], ["Coach Match", "목표에 맞는 프로그램으로 연결합니다."], ["Membership Push", "등록 흐름을 단순하고 세련되게 만듭니다."]],
        offers: [["Club Pass", "시설 자유 이용", "KRW 189,000/mo"], ["Performance PT", "주 2회 코칭", "KRW 620,000/mo"], ["Executive Plan", "라운지·회복 프로그램 포함", "KRW 980,000/mo"]],
        tools: [["코스 추천", "체형과 목표에 맞는 루틴을 제안합니다."], ["운동 기록 분석", "최근 기록 기준 병목을 찾아줍니다."], ["상담 안내", "방문 투어와 등록 조건을 답변합니다."]],
        quote: "고급 회원권이 어떤 경험인지 화면에서 먼저 납득되어야 했습니다.",
        author: "Club Director / VELOCITY ONE",
        panel: { badge: "Membership Match", title: "내 목표용 플랜 찾기", text: "운동 목적과 주당 가능 횟수를 입력하면 추천 플랜과 코칭 구성을 보여줍니다.", rows: [["목표", "체지방 감량"], ["추천 플랜", "Performance PT"], ["가장 빠른 투어", "내일 18:00"]], primary: "투어 예약", secondary: "플랜 보기" },
      },
    ],
  },
];
